import { q, type Question } from './types';

export const ENGLISH_QUESTIONS: Question[] = [
  // ── Grade 1 ──────────────────────────────────────────────────────────────
  q('en-1-001', 1, 'english', 'What colour is the sky on a clear day?', ['Red', 'Blue', 'Black', 'Green'], 1),
  q('en-1-002', 1, 'english', 'A cat says…', ['Moo', 'Meow', 'Quack', 'Roar'], 1),
  q('en-1-003', 1, 'english', 'Which is a fruit?', ['Book', 'Apple', 'Chair', 'Shoe'], 1),
  q('en-1-004', 1, 'english', 'How many legs does a bird usually have?', ['1', '2', '4', '6'], 1),
  q('en-1-005', 1, 'english', 'Opposite of hot:', ['Warm', 'Cold', 'Big', 'Fast'], 1),
  q('en-1-006', 1, 'english', 'We write with a…', ['Spoon', 'Pencil', 'Ball', 'Sock'], 1),
  q('en-1-007', 1, 'english', '\\\\\\\\', [' is used to…', 'Greet', 'Sleep', 'Cry'], 0),
  q('en-1-008', 1, 'english', 'Which animal can fly?', ['Fish', 'Bird', 'Cow', 'Frog'], 1),
  q('en-1-009', 1, 'english', '1 + 1 in words is…', ['Two', 'Three', 'Four', 'Five'], 0),
  q('en-1-010', 1, 'english', 'We drink…', ['Books', 'Water', 'Shoes', 'Clouds'], 1),
  q('en-1-011', 1, 'english', 'Opposite of big:', ['Tall', 'Small', 'Long', 'Fast'], 1),
  q('en-1-012', 1, 'english', 'How many sides does a triangle have?', ['2', '3', '4', '5'], 1),
  q('en-1-013', 1, 'english', 'What do we use to see?', ['Ears', 'Eyes', 'Nose', 'Hands'], 1),
  q('en-1-014', 1, 'english', 'A dog says…', ['Moo', 'Meow', 'Woof', 'Quack'], 2),
  q('en-1-015', 1, 'english', 'Which is a vegetable?', ['Apple', 'Mango', 'Carrot', 'Grape'], 2),
  q('en-1-016', 1, 'english', 'We sleep in a…', ['Kitchen', 'Garden', 'Bedroom', 'Garage'], 2),
  q('en-1-017', 1, 'english', 'Opposite of day:', ['Morning', 'Evening', 'Night', 'Noon'], 2),
  q('en-1-018', 1, 'english', 'We eat with a…', ['Pencil', 'Spoon', 'Ruler', 'Brush'], 1),
  q('en-1-019', 1, 'english', 'Which is red?', ['Grass', 'Sky', 'Apple', 'Lemon'], 2),
  q('en-1-020', 1, 'english', 'How many days are in a week?', ['5', '6', '7', '8'], 2),
  q('en-1-021', 1, 'english', 'Which animal lives in water?', ['Cat', 'Dog', 'Fish', 'Bird'], 2),
  q('en-1-022', 1, 'english', 'Opposite of up:', ['Right', 'Left', 'Down', 'Out'], 2),
  q('en-1-023', 1, 'english', 'We read a…', ['Shoe', 'Book', 'Plate', 'Cup'], 1),
  q('en-1-024', 1, 'english', 'What do we use to hear?', ['Eyes', 'Nose', 'Ears', 'Hands'], 2),
  q('en-1-025', 1, 'english', 'Which comes first in the alphabet?', ['B', 'C', 'A', 'D'], 2),
  q('en-1-026', 1, 'english', 'A cow says…', ['Moo', 'Oink', 'Baa', 'Cluck'], 0),
  q('en-1-027', 1, 'english', 'How many months are in a year?', ['10', '11', '12', '13'], 2),
  q('en-1-028', 1, 'english', 'Opposite of yes:', ['Maybe', 'No', 'Sure', 'Please'], 1),
  q('en-1-029', 1, 'english', 'Which is a colour?', ['Run', 'Yellow', 'Jump', 'Eat'], 1),
  q('en-1-030', 1, 'english', 'We sit on a…', ['Table', 'Chair', 'Window', 'Door'], 1),
  q('en-1-031', 1, 'english', 'Which is a number?', ['Hat', 'Blue', 'Five', 'Run'], 2),
  q('en-1-032', 1, 'english', 'The sun shines in the…', ['Night', 'Rain', 'Day', 'Moon'], 2),
  q('en-1-033', 1, 'english', 'A hen lays…', ['Milk', 'Eggs', 'Wool', 'Honey'], 1),
  q('en-1-034', 1, 'english', 'Opposite of open:', ['Shut', 'New', 'Soft', 'Loud'], 0),
  q('en-1-035', 1, 'english', 'Which is green?', ['Banana', 'Carrot', 'Leaf', 'Apple (red)'], 2),
  q('en-1-036', 1, 'english', 'We wear shoes on our…', ['Hands', 'Head', 'Feet', 'Shoulders'], 2),
  q('en-1-037', 1, 'english', 'Opposite of fast:', ['Tall', 'Slow', 'Loud', 'Big'], 1),
  q('en-1-038', 1, 'english', 'Which animal has a long neck?', ['Dog', 'Giraffe', 'Cat', 'Fish'], 1),
  q('en-1-039', 1, 'english', 'How many letters in the alphabet?', ['24', '25', '26', '27'], 2),
  q('en-1-040', 1, 'english', 'Where do fish live?', ['Trees', 'Sky', 'Water', 'Underground'], 2),
  q('en-1-041', 1, 'english', 'Opposite of in:', ['On', 'Under', 'Out', 'Near'], 2),
  q('en-1-042', 1, 'english', 'A duck says…', ['Moo', 'Quack', 'Bark', 'Hiss'], 1),
  q('en-1-043', 1, 'english', 'Which number comes after 9?', ['8', '10', '11', '7'], 1),
  q('en-1-044', 1, 'english', 'Which is a shape?', ['Red', 'Fast', 'Circle', 'Cold'], 2),
  q('en-1-045', 1, 'english', 'We use an umbrella when it…', ['Shines', 'Rains', 'Snows (only in cold places)', 'Is windy only'], 1),
  q('en-1-046', 1, 'english', 'Opposite of long:', ['Tall', 'Wide', 'Short', 'Round'], 2),
  q('en-1-047', 1, 'english', 'Which is a body part?', ['Table', 'Nose', 'Car', 'Door'], 1),
  q('en-1-048', 1, 'english', 'A frog lives near…', ['Desert', 'Water', 'Snow', 'Fire'], 1),
  q('en-1-049', 1, 'english', 'How many fingers on one hand?', ['3', '4', '5', '6'], 2),
  q('en-1-050', 1, 'english', 'Opposite of clean:', ['Wet', 'Dirty', 'Small', 'Soft'], 1),
  q('en-1-051', 1, 'english', 'We go to school to…', ['Sleep', 'Learn', 'Play only', 'Eat only'], 1),
  q('en-1-052', 1, 'english', 'Which is an animal?', ['Car', 'Pencil', 'Tiger', 'Book'], 2),
  q('en-1-053', 1, 'english', 'The moon appears at…', ['Morning', 'Noon', 'Night', 'Midday'], 2),
  q('en-1-054', 1, 'english', 'Opposite of left:', ['Up', 'Down', 'Right', 'Back'], 2),
  q('en-1-055', 1, 'english', 'We use a brush to…', ['Eat', 'Write', 'Paint', 'Sleep'], 2),
  q('en-1-056', 1, 'english', 'Which has wings?', ['Snake', 'Rabbit', 'Butterfly', 'Dog'], 2),
  q('en-1-057', 1, 'english', 'What colour is the sun?', ['Blue', 'Green', 'Yellow', 'Pink'], 2),
  q('en-1-058', 1, 'english', 'Opposite of soft:', ['Smooth', 'Hard', 'Fluffy', 'Light'], 1),
  q('en-1-059', 1, 'english', 'Which is a school subject?', ['Lunch', 'Maths', 'Chair', 'Door'], 1),
  q('en-1-060', 1, 'english', 'A bee makes…', ['Milk', 'Honey', 'Eggs', 'Cheese'], 1),
  q('en-1-061', 1, 'english', 'Opposite of old:', ['Tall', 'New', 'Short', 'Fast'], 1),
  q('en-1-062', 1, 'english', 'Which do we use to cut?', ['Spoon', 'Scissors', 'Fork', 'Cup'], 1),
  q('en-1-063', 1, 'english', 'Which animal is the largest?', ['Mouse', 'Cat', 'Elephant', 'Dog'], 2),
  q('en-1-064', 1, 'english', 'We wash our hands with…', ['Sand', 'Soap and water', 'Milk', 'Oil'], 1),
  q('en-1-065', 1, 'english', 'What do plants need to grow?', ['Sand and noise', 'Sunlight and water', 'Ice and smoke', 'Toys'], 1),
  q('en-1-066', 1, 'english', 'Opposite of loud:', ['Soft/Quiet', 'Fast', 'Tall', 'Hard'], 0),
  q('en-1-067', 1, 'english', 'Which is a liquid?', ['Stone', 'Wood', 'Water', 'Paper'], 2),
  q('en-1-068', 1, 'english', 'Where do we go when we are sick?', ['School', 'Market', 'Hospital', 'Park'], 2),
  q('en-1-069', 1, 'english', 'Which letter is a vowel?', ['B', 'C', 'A', 'D'], 2),
  q('en-1-070', 1, 'english', 'Opposite of dark:', ['Thin', 'Light/Bright', 'Rough', 'Heavy'], 1),
  q('en-1-071', 1, 'english', 'What do we use to smell?', ['Eyes', 'Ears', 'Nose', 'Tongue'], 2),
  q('en-1-072', 1, 'english', 'Which is a fruit?', ['Tomato (if unsure)', 'Banana', 'Carrot', 'Potato'], 1),
  q('en-1-073', 1, 'english', 'Opposite of thin:', ['Light', 'Fat/Thick', 'Short', 'Soft'], 1),
  q('en-1-074', 1, 'english', 'Which animals gives us milk?', ['Fish', 'Cow', 'Chicken', 'Snake'], 1),
  q('en-1-075', 1, 'english', 'How many vowels are in the alphabet?', ['3', '4', '5', '6'], 2),
  q('en-1-076', 1, 'english', 'We cook food in a…', ['Bedroom', 'Kitchen', 'Library', 'Garage'], 1),
  q('en-1-077', 1, 'english', 'What colour is grass?', ['Yellow', 'Blue', 'Green', 'Red'], 2),
  q('en-1-078', 1, 'english', 'Opposite of empty:', ['Open', 'Wide', 'Full', 'Loud'], 2),
  q('en-1-079', 1, 'english', 'Which is a musical instrument?', ['Table', 'Chair', 'Drum', 'Book'], 2),
  q('en-1-080', 1, 'english', 'We say ', [' when we…', 'Complain', 'Request politely', 'Sleep'], 1),
  q('en-1-081', 1, 'english', 'How many seasons are there?', ['2', '3', '4', '5'], 2),
  q('en-1-082', 1, 'english', 'Which comes last in the alphabet?', ['X', 'Y', 'Z', 'W'], 2),
  q('en-1-083', 1, 'english', 'A sheep makes…', ['Bark', 'Moo', 'Baa', 'Quack'], 2),
  q('en-1-084', 1, 'english', 'Opposite of heavy:', ['Long', 'Light', 'Round', 'Hard'], 1),
  q('en-1-085', 1, 'english', 'What do we say when we leave?', ['Hello', 'Goodbye', 'Thank you', 'Please'], 1),
  q('en-1-086', 1, 'english', 'Which is made of wood?', ['Glass cup', 'Metal spoon', 'Wooden chair', 'Plastic bag'], 2),
  q('en-1-087', 1, 'english', 'Which number comes before 5?', ['3', '4', '6', '7'], 1),
  q('en-1-088', 1, 'english', 'What do we use to taste?', ['Eyes', 'Nose', 'Tongue', 'Ears'], 2),
  q('en-1-089', 1, 'english', 'Opposite of morning:', ['Afternoon', 'Night/Evening', 'Midday', 'Dawn'], 1),
  q('en-1-090', 1, 'english', 'Which is a toy?', ['Plate', 'Teddy bear', 'Fork', 'Soap'], 1),
  q('en-1-091', 1, 'english', 'What do birds live in?', ['Cave', 'Nest', 'Burrow', 'Den'], 1),
  q('en-1-092', 1, 'english', 'Opposite of sweet:', ['Sour/Bitter', 'Tasty', 'Soft', 'Small'], 0),
  q('en-1-093', 1, 'english', 'Which is a sport?', ['Painting', 'Reading', 'Football', 'Sleeping'], 2),
  q('en-1-094', 1, 'english', 'Where does a rabbit live?', ['Tree', 'River', 'Burrow', 'Sky'], 2),
  q(`en-1-095`, 1, `english`, `What do we say to someone who is sad?`, [`Happy birthday`, `Don\\'t worry`, `Goodbye`, `Hello`], 1),
  q('en-1-096', 1, 'english', 'Which has four legs?', ['Bird', 'Fish', 'Snake', 'Dog'], 3),
  q('en-1-097', 1, 'english', 'What is the first letter of the alphabet?', ['B', 'C', 'A', 'D'], 2),
  q('en-1-098', 1, 'english', 'Which is a season?', ['Monday', 'Spring', 'Red', 'Dog'], 1),
  q('en-1-099', 1, 'english', 'We say \\\\\\\\', [' when we…', 'Win a prize', 'Make a mistake', 'Go to sleep'], 1),
  q('en-1-100', 1, 'english', 'Which is a planet?', ['Moon', 'Sun', 'Earth', 'Star'], 2),

  // ── Grade 2 ──────────────────────────────────────────────────────────────
  q('en-2-001', 2, 'english', 'Plural of cat:', ['Cat', 'Cats', 'Cates', 'Caties'], 1),
  q('en-2-002', 2, 'english', 'She ___ a student.', ['am', 'is', 'are', 'be'], 1),
  q('en-2-003', 2, 'english', 'Opposite of big:', ['Tall', 'Small', 'Long', 'Fast'], 1),
  q('en-2-004', 2, 'english', 'Which day comes after Monday?', ['Sunday', 'Tuesday', 'Friday', 'Saturday'], 1),
  q('en-2-005', 2, 'english', 'A baby dog is called a…', ['Kitten', 'Puppy', 'Cub', 'Chick'], 1),
  q('en-2-006', 2, 'english', 'Reply to "Thank you":', ['Sorry', "You're welcome", 'Goodbye', 'Help'], 1),
  q('en-2-007', 2, 'english', 'We sleep in a…', ['Kitchen', 'Bedroom', 'Garden', 'Bus stop'], 1),
  q('en-2-008', 2, 'english', 'Choose the noun:', ['Run', 'Happy', 'Teacher', 'Quickly'], 2),
  q('en-2-009', 2, 'english', 'I ___ to school every day.', ['go', 'goes', 'going', 'gone'], 0),
  q('en-2-010', 2, 'english', 'Which is a colour?', ['Happy', 'Yellow', 'Jump', 'Soft'], 1),
  q('en-2-011', 2, 'english', 'Plural of dog:', ['Dogges', 'Doges', 'Dogs', 'Dogss'], 2),
  q('en-2-012', 2, 'english', 'He ___ a teacher.', ['am', 'is', 'are', 'be'], 1),
  q('en-2-013', 2, 'english', 'Opposite of fast:', ['Big', 'Tall', 'Slow', 'Long'], 2),
  q('en-2-014', 2, 'english', 'Which day comes after Wednesday?', ['Tuesday', 'Thursday', 'Friday', 'Monday'], 1),
  q('en-2-015', 2, 'english', 'A baby cat is called a…', ['Pup', 'Kitten', 'Cub', 'Chick'], 1),
  q('en-2-016', 2, 'english', 'Reply to "Sorry":', ['Goodbye', "It's ok", 'Hello', 'Yes'], 1),
  q('en-2-017', 2, 'english', 'We cook in a…', ['Bedroom', 'Bathroom', 'Kitchen', 'Library'], 2),
  q('en-2-018', 2, 'english', 'Choose the verb:', ['Book', 'Happy', 'Chair', 'Run'], 3),
  q('en-2-019', 2, 'english', 'They ___ happy.', ['am', 'is', 'are', 'be'], 2),
  q('en-2-020', 2, 'english', 'Which is a shape?', ['Red', 'Circle', 'Fast', 'Loud'], 1),
  q('en-2-021', 2, 'english', 'Plural of book:', ['Bookies', 'Book', 'Books', 'Booken'], 2),
  q('en-2-022', 2, 'english', 'We ___ happy today.', ['am', 'is', 'are', 'be'], 2),
  q('en-2-023', 2, 'english', 'Opposite of tall:', ['Small', 'Short', 'Fast', 'Dark'], 1),
  q('en-2-024', 2, 'english', 'Which month comes after January?', ['December', 'February', 'March', 'November'], 1),
  q('en-2-025', 2, 'english', 'A baby horse is called a…', ['Cub', 'Lamb', 'Foal', 'Calf'], 2),
  q('en-2-026', 2, 'english', 'Where do we borrow books?', ['Hospital', 'Library', 'School canteen', 'Market'], 1),
  q('en-2-027', 2, 'english', 'Choose the adjective:', ['Run', 'Jump', 'Beautiful', 'Walk'], 2),
  q('en-2-028', 2, 'english', 'She ___ a book yesterday.', ['read', 'reads', 'reading', 'readed'], 0),
  q('en-2-029', 2, 'english', 'Which is a number?', ['Blue', 'Fast', 'Twenty', 'Round'], 2),
  q('en-2-030', 2, 'english', 'Plural of box:', ['Boxs', 'Boxies', 'Boxes', 'Boxen'], 2),
  q('en-2-031', 2, 'english', 'The dog ___ every morning.', ['bark', 'barked', 'barks', 'barking'], 2),
  q('en-2-032', 2, 'english', 'Opposite of young:', ['Short', 'Old', 'Small', 'Weak'], 1),
  q('en-2-033', 2, 'english', 'Which day comes before Saturday?', ['Sunday', 'Thursday', 'Friday', 'Monday'], 2),
  q('en-2-034', 2, 'english', 'A baby cow is called a…', ['Lamb', 'Foal', 'Cub', 'Calf'], 3),
  q('en-2-035', 2, 'english', 'We study at a…', ['Hospital', 'Market', 'School', 'Park'], 2),
  q('en-2-036', 2, 'english', 'Choose the noun:', ['Quickly', 'Slowly', 'Happy', 'Chair'], 3),
  q('en-2-037', 2, 'english', 'He ___ a mango now.', ['eating', 'is eating', 'eats', 'eaten'], 1),
  q('en-2-038', 2, 'english', 'Which is a season?', ['Monday', 'Autumn', 'Blue', 'Dog'], 1),
  q('en-2-039', 2, 'english', 'Plural of fish:', ['Fishs', 'Fishies', 'Fishes/Fish', 'Fishss'], 2),
  q('en-2-040', 2, 'english', 'I ___ happy now.', ['am', 'is', 'are', 'be'], 0),
  q('en-2-041', 2, 'english', 'Opposite of hot:', ['Cold', 'Small', 'Long', 'Thin'], 0),
  q('en-2-042', 2, 'english', 'Which comes after Sunday?', ['Saturday', 'Monday', 'Friday', 'Tuesday'], 1),
  q('en-2-043', 2, 'english', 'A baby bird is called a…', ['Pup', 'Cub', 'Chick', 'Calf'], 2),
  q('en-2-044', 2, 'english', 'Choose the adjective:', ['Run', 'Tall', 'Jump', 'Swim'], 1),
  q('en-2-045', 2, 'english', 'She ___ a cake tomorrow.', ['bake', 'baked', 'will bake', 'bakes'], 2),
  q('en-2-046', 2, 'english', 'Which is a day?', ['April', 'Orange', 'Monday', 'Summer'], 2),
  q('en-2-047', 2, 'english', 'Plural of tooth:', ['Tooths', 'Teethes', 'Teeth', 'Toothes'], 2),
  q('en-2-048', 2, 'english', 'The girls ___ playing.', ['is', 'am', 'are', 'be'], 2),
  q('en-2-049', 2, 'english', 'Opposite of short:', ['Light', 'Tall/Long', 'Big', 'Fast'], 1),
  q('en-2-050', 2, 'english', 'Which month has the fewest days?', ['March', 'February', 'April', 'June'], 1),
  q('en-2-051', 2, 'english', 'A baby sheep is called a…', ['Calf', 'Foal', 'Lamb', 'Pup'], 2),
  q('en-2-052', 2, 'english', 'Choose the verb:', ['Fast', 'Book', 'Swim', 'Blue'], 2),
  q('en-2-053', 2, 'english', 'He ___ at school yesterday.', ['is', 'are', 'was', 'were'], 2),
  q('en-2-054', 2, 'english', 'Which is a month?', ['Monday', 'Summer', 'March', 'Sunday'], 2),
  q('en-2-055', 2, 'english', 'Plural of child:', ['Childs', 'Children', 'Childes', 'Childrens'], 1),
  q('en-2-056', 2, 'english', 'She ___ her homework now.', ['do', 'did', 'doing', 'is doing'], 3),
  q('en-2-057', 2, 'english', 'Opposite of dry:', ['Small', 'Wet', 'Hard', 'Cold'], 1),
  q('en-2-058', 2, 'english', 'Which day comes after Thursday?', ['Wednesday', 'Saturday', 'Friday', 'Monday'], 2),
  q('en-2-059', 2, 'english', 'A baby lion is called a…', ['Pup', 'Chick', 'Cub', 'Lamb'], 2),
  q('en-2-060', 2, 'english', 'We borrow books from a…', ['Pharmacy', 'Library', 'Canteen', 'Clinic'], 1),
  q('en-2-061', 2, 'english', 'Choose the adjective:', ['Sleep', 'Quickly', 'Funny', 'Run'], 2),
  q('en-2-062', 2, 'english', 'They ___ at home yesterday.', ['is', 'am', 'was', 'were'], 3),
  q('en-2-063', 2, 'english', 'Which is a plant?', ['Cat', 'Fish', 'Rose', 'Dog'], 2),
  q('en-2-064', 2, 'english', 'Plural of man:', ['Mans', 'Men', 'Manes', 'Menes'], 1),
  q('en-2-065', 2, 'english', 'I ___ a letter yesterday.', ['write', 'writes', 'wrote', 'written'], 2),
  q('en-2-066', 2, 'english', 'Opposite of near:', ['Small', 'Far', 'High', 'Wide'], 1),
  q('en-2-067', 2, 'english', 'Which comes before Tuesday?', ['Wednesday', 'Thursday', 'Monday', 'Friday'], 2),
  q('en-2-068', 2, 'english', 'A baby pig is called a…', ['Cub', 'Piglet', 'Foal', 'Lamb'], 1),
  q('en-2-069', 2, 'english', 'Choose the noun:', ['Swim', 'Quick', 'River', 'Slowly'], 2),
  q('en-2-070', 2, 'english', 'She ___ at the zoo now.', ['is', 'are', 'am', 'were'], 0),
  q('en-2-071', 2, 'english', 'Which is a tool?', ['Apple', 'Dog', 'Hammer', 'Chair'], 2),
  q('en-2-072', 2, 'english', 'Plural of woman:', ['Womans', 'Women', 'Womens', 'Womanes'], 1),
  q('en-2-073', 2, 'english', 'He ___ football every evening.', ['play', 'playing', 'plays', 'played'], 2),
  q('en-2-074', 2, 'english', 'Opposite of begin:', ['Start', 'End', 'Run', 'Jump'], 1),
  q('en-2-075', 2, 'english', 'Which month comes after March?', ['February', 'May', 'April', 'June'], 2),
  q('en-2-076', 2, 'english', 'A baby goat is called a…', ['Kid', 'Foal', 'Lamb', 'Calf'], 0),
  q('en-2-077', 2, 'english', 'Choose the verb:', ['House', 'Quickly', 'Green', 'Jump'], 3),
  q('en-2-078', 2, 'english', 'We ___ at the party last night.', ['dance', 'dances', 'danced', 'dancing'], 2),
  q('en-2-079', 2, 'english', 'Which is a weather word?', ['Chair', 'Monday', 'Rainy', 'School'], 2),
  q('en-2-080', 2, 'english', 'Plural of mouse:', ['Mouses', 'Mousies', 'Mice', 'Moose'], 2),
  q('en-2-081', 2, 'english', 'The boy ___ to school.', ['go', 'goes', 'going', 'gone'], 1),
  q('en-2-082', 2, 'english', 'Opposite of happy:', ['Jolly', 'Sad', 'Excited', 'Calm'], 1),
  q('en-2-083', 2, 'english', 'Which day comes after Friday?', ['Monday', 'Thursday', 'Saturday', 'Tuesday'], 2),
  q('en-2-084', 2, 'english', 'A baby kangaroo is called a…', ['Pup', 'Joey', 'Cub', 'Kit'], 1),
  q('en-2-085', 2, 'english', 'Choose the adjective:', ['Walk', 'Slowly', 'Bright', 'Swim'], 2),
  q('en-2-086', 2, 'english', 'They ___ a song tomorrow.', ['sing', 'sings', 'will sing', 'singing'], 2),
  q('en-2-087', 2, 'english', 'Which is a sport?', ['Sleeping', 'Reading', 'Swimming', 'Eating'], 2),
  q('en-2-088', 2, 'english', 'Plural of foot:', ['Foots', 'Feetes', 'Feet', 'Footes'], 2),
  q('en-2-089', 2, 'english', 'She ___ a nurse.', ['am', 'is', 'are', 'be'], 1),
  q('en-2-090', 2, 'english', 'Opposite of quiet:', ['Soft', 'Loud', 'Light', 'Thin'], 1),
  q('en-2-091', 2, 'english', 'Which month comes after June?', ['May', 'August', 'July', 'September'], 2),
  q('en-2-092', 2, 'english', 'A baby deer is called a…', ['Cub', 'Lamb', 'Fawn', 'Kid'], 2),
  q('en-2-093', 2, 'english', 'Choose the noun:', ['Run', 'Big', 'City', 'Quickly'], 2),
  q('en-2-094', 2, 'english', 'We ___ dinner at six yesterday.', ['have', 'has', 'had', 'having'], 2),
  q('en-2-095', 2, 'english', 'Which is an insect?', ['Dog', 'Fish', 'Butterfly', 'Cat'], 2),
  q('en-2-096', 2, 'english', 'Plural of goose:', ['Gooses', 'Geese', 'Goosies', 'Goosen'], 1),
  q('en-2-097', 2, 'english', 'He ___ very tall.', ['am', 'is', 'are', 'be'], 1),
  q('en-2-098', 2, 'english', 'Opposite of rich:', ['Strong', 'Poor', 'Happy', 'Fast'], 1),
  q('en-2-099', 2, 'english', 'Which comes after December?', ['November', 'January', 'February', 'October'], 1),
  q('en-2-100', 2, 'english', 'Choose the verb:', ['Book', 'Happy', 'Round', 'Fly'], 3),

  // ── Grade 3 ──────────────────────────────────────────────────────────────
  q('en-3-001', 3, 'english', 'Past tense of play:', ['Played', 'Playing', 'Plays', 'Play'], 0),
  q('en-3-002', 3, 'english', 'They ___ happy.', ['is', 'am', 'are', 'be'], 2),
  q('en-3-003', 3, 'english', 'Synonym of happy:', ['Sad', 'Glad', 'Angry', 'Tired'], 1),
  q('en-3-004', 3, 'english', 'A person who teaches is a…', ['Doctor', 'Teacher', 'Driver', 'Pilot'], 1),
  q('en-3-005', 3, 'english', 'Choose correct article: ___ apple', ['a', 'an', 'the only', 'no'], 1),
  q('en-3-006', 3, 'english', 'Antonym of fast:', ['Quick', 'Slow', 'Rapid', 'Swift'], 1),
  q('en-3-007', 3, 'english', '\\\\\\', [' — \\\\', ' shows…', 'Ability', 'Colour'], 0),
  q('en-3-008', 3, 'english', 'Comparative of tall:', ['Taller', 'Tallest', 'More tall', 'Tall'], 0),
  q('en-3-009', 3, 'english', 'Which is a question word?', ['Where', 'Book', 'Green', 'Softly'], 0),
  q('en-3-010', 3, 'english', 'She has two ___.', ['foot', 'feet', 'feets', 'foots'], 1),
  q('en-3-011', 3, 'english', 'Past tense of run:', ['Runned', 'Ran', 'Running', 'Run'], 1),
  q('en-3-012', 3, 'english', 'Synonym of big:', ['Small', 'Little', 'Large', 'Thin'], 2),
  q('en-3-013', 3, 'english', 'Choose correct article: ___ elephant', ['a', 'an', 'the only', 'no'], 1),
  q('en-3-014', 3, 'english', 'A doctor works in a…', ['School', 'Market', 'Hospital', 'Library'], 2),
  q('en-3-015', 3, 'english', 'Antonym of bright:', ['Light', 'Dark', 'Clear', 'Shiny'], 1),
  q('en-3-016', 3, 'english', 'Comparative of small:', ['Smaller', 'Smallest', 'More small', 'Small'], 0),
  q('en-3-017', 3, 'english', '\\\\', [' — \\\\', ' shows…', 'Permission', 'Ability'], 2),
  q('en-3-018', 3, 'english', 'Past tense of write:', ['Writed', 'Wrote', 'Writing', 'Write'], 1),
  q('en-3-019', 3, 'english', 'Synonym of angry:', ['Calm', 'Furious', 'Gentle', 'Quiet'], 1),
  q('en-3-020', 3, 'english', 'A pilot flies a…', ['Ship', 'Car', 'Plane', 'Train'], 2),
  q('en-3-021', 3, 'english', 'Choose correct article: ___ uniform', ['a', 'an', 'the only', 'no'], 0),
  q('en-3-022', 3, 'english', 'Antonym of rich:', ['Wealthy', 'Poor', 'Strong', 'Fast'], 1),
  q('en-3-023', 3, 'english', 'Superlative of tall:', ['Taller', 'Tallest', 'Most tall', 'More tall'], 1),
  q('en-3-024', 3, 'english', '\\', [' — \\\\', ' shows…', 'Obligation', 'Permission'], 1),
  q('en-3-025', 3, 'english', 'Past tense of eat:', ['Eated', 'Eaten', 'Ate', 'Eating'], 2),
  q('en-3-026', 3, 'english', 'Synonym of sad:', ['Happy', 'Joyful', 'Unhappy', 'Excited'], 2),
  q('en-3-027', 3, 'english', 'A librarian works in a…', ['Hospital', 'Library', 'Factory', 'School only'], 1),
  q('en-3-028', 3, 'english', 'Choose correct article: ___ hour', ['a', 'an', 'the only', 'no'], 1),
  q('en-3-029', 3, 'english', 'Antonym of ancient:', ['Old', 'Modern', 'Historic', 'Vintage'], 1),
  q('en-3-030', 3, 'english', 'Comparative of beautiful:', ['Beautifuler', 'More beautiful', 'Beautifullest', 'Beautifuller'], 1),
  q('en-3-031', 3, 'english', '\\\\', [' — future is shown by…', 'will', 'help', 'I'], 0),
  q('en-3-032', 3, 'english', 'Past tense of see:', ['Seen', 'Saw', 'Seeing', 'Sees'], 1),
  q('en-3-033', 3, 'english', 'Synonym of small:', ['Huge', 'Little', 'Tall', 'Wide'], 1),
  q('en-3-034', 3, 'english', 'A chef cooks in a…', ['Office', 'Laboratory', 'Kitchen', 'Studio'], 2),
  q('en-3-035', 3, 'english', 'Choose correct article: ___ orange', ['a', 'an', 'the only', 'no'], 1),
  q('en-3-036', 3, 'english', 'Antonym of love:', ['Like', 'Hate', 'Prefer', 'Enjoy'], 1),
  q('en-3-037', 3, 'english', 'Superlative of good:', ['Gooder', 'Goodest', 'Best', 'Better'], 2),
  q('en-3-038', 3, 'english', '\\', [' — \\\\', ' gives…', 'Order', 'Ability'], 2),
  q('en-3-039', 3, 'english', 'Past tense of go:', ['Goed', 'Goes', 'Went', 'Gone'], 2),
  q('en-3-040', 3, 'english', 'Synonym of cold:', ['Warm', 'Hot', 'Chilly', 'Sunny'], 2),
  q('en-3-041', 3, 'english', 'A farmer works on a…', ['Ship', 'Farm', 'Hospital', 'Library'], 1),
  q('en-3-042', 3, 'english', 'Choose correct article: ___ umbrella', ['a', 'an', 'the only', 'no'], 1),
  q('en-3-043', 3, 'english', 'Antonym of strong:', ['Powerful', 'Weak', 'Hard', 'Tough'], 1),
  q('en-3-044', 3, 'english', 'Comparative of bad:', ['Worse', 'Worst', 'Badder', 'More bad'], 0),
  q('en-3-045', 3, 'english', '\\\\', [' — What type of sentence?', 'Statement', 'Question', 'Command'], 1),
  q('en-3-046', 3, 'english', 'Past tense of come:', ['Comed', 'Came', 'Coming', 'Come'], 1),
  q('en-3-047', 3, 'english', 'Synonym of tired:', ['Energetic', 'Sleepy', 'Happy', 'Calm'], 1),
  q('en-3-048', 3, 'english', 'An engineer builds…', ['Meals', 'Books', 'Structures/machines', 'Laws'], 2),
  q('en-3-049', 3, 'english', 'Choose correct article: ___ egg', ['a', 'an', 'the only', 'no'], 1),
  q('en-3-050', 3, 'english', 'Antonym of lose:', ['Fail', 'Win', 'Drop', 'Miss'], 1),
  q('en-3-051', 3, 'english', 'Superlative of bad:', ['Worse', 'Worst', 'Badder', 'Baddest'], 1),
  q('en-3-052', 3, 'english', '\\\\', [' — What type of sentence?', 'Question', 'Statement', 'Command'], 2),
  q('en-3-053', 3, 'english', 'Past tense of take:', ['Taked', 'Tooken', 'Took', 'Taking'], 2),
  q('en-3-054', 3, 'english', 'Synonym of brave:', ['Fearful', 'Courageous', 'Shy', 'Tired'], 1),
  q('en-3-055', 3, 'english', 'A dentist treats…', ['Eyes', 'Teeth', 'Ears', 'Legs'], 1),
  q('en-3-056', 3, 'english', 'Choose correct article: ___ university', ['a', 'an', 'the only', 'no'], 0),
  q('en-3-057', 3, 'english', 'Antonym of easy:', ['Simple', 'Hard', 'Clear', 'Plain'], 1),
  q('en-3-058', 3, 'english', 'Comparative of far:', ['Farrer', 'Further/Farther', 'Most far', 'Far more'], 1),
  q('en-3-059', 3, 'english', '\\\\', [' — type of sentence?', 'Question', 'Statement', 'Command'], 3),
  q('en-3-060', 3, 'english', 'Past tense of give:', ['Gived', 'Gave', 'Given', 'Giving'], 1),
  q('en-3-061', 3, 'english', 'Synonym of fast:', ['Slow', 'Quiet', 'Quick', 'Heavy'], 2),
  q('en-3-062', 3, 'english', 'A mechanic repairs…', ['Animals', 'Books', 'Vehicles/engines', 'Teeth'], 2),
  q('en-3-063', 3, 'english', 'Choose correct article: ___ honest man', ['a', 'an', 'the only', 'no'], 1),
  q('en-3-064', 3, 'english', 'Antonym of first:', ['Second', 'Third', 'Last', 'Next'], 2),
  q('en-3-065', 3, 'english', 'Superlative of beautiful:', ['More beautiful', 'Most beautiful', 'Beautifuller', 'Beautifulest'], 1),
  q('en-3-066', 3, 'english', '\\\\', [' — This is…', 'Direct speech', 'Reported speech', 'A question'], 1),
  q('en-3-067', 3, 'english', 'Past tense of make:', ['Maked', 'Making', 'Made', 'Makes'], 2),
  q('en-3-068', 3, 'english', 'Synonym of beautiful:', ['Ugly', 'Pretty', 'Awful', 'Dull'], 1),
  q(`en-3-069`, 3, `english`, `A pilot\`s workplace:`, [`Hospital`, `Cockpit/Plane`, `Factory`, `Farm`], 1),
  q('en-3-070', 3, 'english', 'Choose correct article: ___ car', ['an', 'a', 'the only', 'no'], 1),
  q('en-3-071', 3, 'english', 'Antonym of always:', ['Often', 'Usually', 'Never', 'Sometimes'], 2),
  q('en-3-072', 3, 'english', 'Comparative of many:', ['Manyer', 'More', 'Most', 'Morer'], 1),
  q('en-3-073', 3, 'english', '\\\\\\\\', [' — type of sentence?', 'Question', 'Exclamation', 'Statement'], 3),
  q('en-3-074', 3, 'english', 'Past tense of know:', ['Knowed', 'Knew', 'Known', 'Knowing'], 1),
  q('en-3-075', 3, 'english', 'Synonym of quiet:', ['Loud', 'Noisy', 'Silent', 'Cheerful'], 2),
  q('en-3-076', 3, 'english', 'An optician tests…', ['Hearing', 'Eyesight', 'Teeth', 'Blood pressure'], 1),
  q('en-3-077', 3, 'english', 'Choose correct article: ___ island', ['an', 'a', 'the only', 'no'], 1),
  q('en-3-078', 3, 'english', 'Antonym of inside:', ['Under', 'Above', 'Outside', 'Near'], 2),
  q('en-3-079', 3, 'english', 'Superlative of many:', ['Maniest', 'Most', 'More', 'Manyest'], 1),
  q('en-3-080', 3, 'english', '\\\\\\\\', [' — This is…', 'Direct speech', 'Reported speech', 'A question'], 1),
  q('en-3-081', 3, 'english', 'Past tense of buy:', ['Buyed', 'Boughten', 'Bought', 'Buying'], 2),
  q('en-3-082', 3, 'english', 'Synonym of smart:', ['Dull', 'Foolish', 'Clever', 'Slow'], 2),
  q('en-3-083', 3, 'english', 'A police officer keeps…', ['Patients well', 'Buildings standing', 'Order/peace', 'Books available'], 2),
  q('en-3-084', 3, 'english', 'Choose correct article: ___ youth', ['an', 'a', 'the only', 'no'], 1),
  q('en-3-085', 3, 'english', 'Antonym of begin:', ['Start', 'Open', 'End', 'Continue'], 2),
  q('en-3-086', 3, 'english', 'Comparative of little (amount):', ['Littler', 'Less', 'Least', 'More little'], 1),
  q('en-3-087', 3, 'english', 'Which is a preposition?', ['Run', 'Happy', 'Under', 'Quickly'], 2),
  q('en-3-088', 3, 'english', 'Past tense of think:', ['Thinked', 'Thought', 'Thinking', 'Thinks'], 1),
  q('en-3-089', 3, 'english', 'Synonym of rich:', ['Poor', 'Wealthy', 'Thin', 'Weak'], 1),
  q('en-3-090', 3, 'english', 'A judge works in a…', ['Market', 'Court', 'Hospital', 'Farm'], 1),
  q('en-3-091', 3, 'english', 'Choose correct article: ___ one-way road', ['an', 'a', 'the only', 'no'], 1),
  q('en-3-092', 3, 'english', 'Antonym of friend:', ['Ally', 'Partner', 'Enemy', 'Buddy'], 2),
  q('en-3-093', 3, 'english', 'Superlative of little (amount):', ['Littler', 'Less', 'Least', 'Littlest'], 2),
  q('en-3-094', 3, 'english', 'Which is a conjunction?', ['And', 'Run', 'Blue', 'Quickly'], 0),
  q('en-3-095', 3, 'english', 'Past tense of feel:', ['Feeled', 'Felt', 'Feeling', 'Feels'], 1),
  q('en-3-096', 3, 'english', 'Synonym of begin:', ['End', 'Finish', 'Start', 'Stop'], 2),
  q('en-3-097', 3, 'english', 'A painter works with…', ['Medicine', 'Bricks', 'Paintbrush and colours', 'Wires'], 2),
  q('en-3-098', 3, 'english', 'Choose correct article: ___ European city', ['an', 'a', 'the only', 'no'], 1),
  q('en-3-099', 3, 'english', 'Antonym of fail:', ['Miss', 'Drop', 'Succeed', 'Lose'], 2),
  q('en-3-100', 3, 'english', 'Comparative of good:', ['Gooder', 'Best', 'Better', 'More good'], 2),

  // ── Grade 4 ──────────────────────────────────────────────────────────────
  q('en-4-001', 4, 'english', 'Past tense of go:', ['Goed', 'Went', 'Gone', 'Going'], 1),
  q('en-4-002', 4, 'english', '\\\\\\\\', [' is a…', 'Noun', 'Adjective', 'Verb'], 1),
  q('en-4-003', 4, 'english', 'Choose conjunction: I like tea ___ coffee.', ['and', 'very', 'soonly', 'the'], 0),
  q('en-4-004', 4, 'english', 'Homophone of \\\\\\\\', [':', 'Sea', 'Saw', 'Seen'], 0),
  q('en-4-005', 4, 'english', 'Superlative of good:', ['Gooder', 'Best', 'Better', 'Most good'], 1),
  q('en-4-006', 4, 'english', '\\\\\\\\', [' is an…', 'Adjective', 'Adverb', 'Noun'], 1),
  q('en-4-007', 4, 'english', 'Plural of child:', ['Childs', 'Children', 'Childes', 'Childrens'], 1),
  q('en-4-008', 4, 'english', 'Correct: She ___ yesterday.', ['walk', 'walked', 'walking', 'walks'], 1),
  q('en-4-009', 4, 'english', 'Prefix un- in \\\\\\\\', [' means…', 'Very', 'Not', 'Again'], 1),
  q(`en-4-010`, 4, `english`, `A story\\'s main person is the…`, [`Villain only`, `Character/hero`, `Publisher`, `Font`], 1),
  q('en-4-011', 4, 'english', 'Homophone of \\\\\\\\', [':', 'Too/Two', 'To', 'Top'], 0),
  q('en-4-012', 4, 'english', '\\\\\\\\', [' is a/an…', 'Noun', 'Adjective', 'Verb'], 3),
  q('en-4-013', 4, 'english', 'Choose conjunction: She was tired, ___ she kept going.', ['and', 'but', 'so', 'or'], 1),
  q('en-4-014', 4, 'english', 'Prefix re- in \\\\\\\\', [' means…', 'Not', 'Before', 'Again'], 2),
  q('en-4-015', 4, 'english', 'Past tense of begin:', ['Begined', 'Begun', 'Began', 'Beginning'], 2),
  q('en-4-016', 4, 'english', 'Homophone of \\\\\\\\', [':', 'Hear', 'Hair', 'Hare'], 0),
  q('en-4-017', 4, 'english', '\\\\\\\\', [' — \\\\\\\\', ' is a/an…', 'Noun', 'Verb'], 2),
  q('en-4-018', 4, 'english', 'Choose conjunction: I will go ___ it rains.', ['although', 'even if', 'because', 'unless'], 3),
  q('en-4-019', 4, 'english', 'Suffix -less means…', ['Full of', 'Without', 'Again', 'Not'], 1),
  q('en-4-020', 4, 'english', 'Past tense of break:', ['Breaked', 'Broke', 'Broken', 'Breaking'], 1),
  q('en-4-021', 4, 'english', 'Homophone of \\\\\\\\', [':', 'Write', 'Ride', 'Rise'], 0),
  q('en-4-022', 4, 'english', '\\\\\\\\', [' — \\\\\\\\', ' is a/an…', 'Adjective', 'Noun'], 2),
  q('en-4-023', 4, 'english', 'Choose conjunction: ___ she studied hard, she failed.', ['Although', 'Because', 'So', 'And'], 0),
  q('en-4-024', 4, 'english', 'Suffix -ful means…', ['Without', 'Full of/Characterised by', 'Before', 'After'], 1),
  q('en-4-025', 4, 'english', 'Past tense of teach:', ['Teached', 'Thought', 'Taught', 'Teaching'], 2),
  q('en-4-026', 4, 'english', 'Homophone of \\\\\\\\', [':', 'Now', 'Know', 'Not'], 1),
  q('en-4-027', 4, 'english', '\\\\\\\\', [' — \\\\\\\\', ' modifies…', 'He (noun)', 'Runs (verb)'], 1),
  q('en-4-028', 4, 'english', 'Choose conjunction: She left ___ she was tired.', ['although', 'but', 'because', 'yet'], 2),
  q('en-4-029', 4, 'english', 'Prefix mis- in \\\\\\\\', [' means…', 'Again', 'Not', 'Wrongly'], 2),
  q('en-4-030', 4, 'english', 'Past tense of choose:', ['Choosed', 'Chosen', 'Chose', 'Choosing'], 2),
  q('en-4-031', 4, 'english', 'Homophone of \\\\\\\\', [':', 'Floor', 'Flour', 'Flow'], 1),
  q('en-4-032', 4, 'english', '\\\\\\', [' — \\\\', ' is a/an…', 'Noun', 'Adjective'], 2),
  q('en-4-033', 4, 'english', 'Choose conjunction: Take an umbrella ___ it rains.', ['because', 'in case', 'although', 'yet'], 1),
  q('en-4-034', 4, 'english', 'Suffix -ness changes…', ['Verb to noun', 'Adjective to noun', 'Noun to verb', 'Noun to adverb'], 1),
  q('en-4-035', 4, 'english', 'Past tense of fly:', ['Flied', 'Flown', 'Flew', 'Flying'], 2),
  q('en-4-036', 4, 'english', 'Homophone of \\\\', [':', 'Pear', 'Pier', 'Per'], 0),
  q('en-4-037', 4, 'english', '\\', [' — \\\\', ' is a/an…', 'Adverb', 'Verb'], 2),
  q('en-4-038', 4, 'english', 'Choose conjunction: He is smart ___ lazy.', ['and', 'so', 'but', 'because'], 2),
  q('en-4-039', 4, 'english', 'Prefix dis- in \\\\', [' means…', 'Again', 'Very', 'Not/opposite'], 2),
  q('en-4-040', 4, 'english', 'Past tense of draw:', ['Drawed', 'Drawn', 'Drew', 'Drawing'], 2),
  q('en-4-041', 4, 'english', 'Homophone of \\\\', [':', 'Sun', 'Sin', 'Sen'], 0),
  q('en-4-042', 4, 'english', '\\\\', [' — \\\\', ' modifies…', 'She', 'answered (verb)'], 1),
  q('en-4-043', 4, 'english', 'Choose conjunction: ___ you study hard, you will pass.', ['Although', 'If', 'But', 'So'], 1),
  q('en-4-044', 4, 'english', 'Suffix -tion changes…', ['Adjective to adverb', 'Verb to noun', 'Noun to verb', 'Noun to adjective'], 1),
  q('en-4-045', 4, 'english', 'Past tense of steal:', ['Stealed', 'Stoled', 'Stole', 'Stealing'], 2),
  q('en-4-046', 4, 'english', 'Homophone of \\\\', [':', 'I', 'Is', 'In'], 0),
  q('en-4-047', 4, 'english', '\\\\', [' — \\\\', ' here is a/an…', 'Adjective', 'Adverb'], 1),
  q('en-4-048', 4, 'english', 'Choose conjunction: She ___ her brother are here.', ['and', 'with', 'beside', 'near'], 0),
  q('en-4-049', 4, 'english', 'Prefix over- in \\\\', [' means…', 'Under', 'Again', 'Too much'], 2),
  q('en-4-050', 4, 'english', 'Past tense of hide:', ['Hided', 'Hidden', 'Hid', 'Hiding'], 2),
  q('en-4-051', 4, 'english', 'Homophone of \\\\', [':', 'Not', 'Note', 'Nod'], 0),
  q('en-4-052', 4, 'english', '\\', [' — \\\\', ' describes…', 'She (noun)', 'Danced (verb)'], 1),
  q('en-4-053', 4, 'english', "Choose conjunction: She wants to go, ___ she can't.", ['and', 'so', 'but', 'because'], 2),
  q('en-4-054', 4, 'english', 'Suffix -er can mean…', ['Without', 'Full of', 'One who does an action', 'Not'], 2),
  q('en-4-055', 4, 'english', 'Past tense of grow:', ['Growed', 'Grown', 'Grew', 'Growing'], 2),
  q('en-4-056', 4, 'english', 'Homophone of \\', [':', 'Piece', 'Place', 'Pace'], 0),
  q('en-4-057', 4, 'english', '\\\\\\', [' — \\\\', ' modifies…', 'Building (noun)', 'Tall (adjective)'], 1),
  q('en-4-058', 4, 'english', 'Choose conjunction: Work hard ___ you will succeed.', ['or', 'and', 'but', 'yet'], 1),
  q('en-4-059', 4, 'english', 'Prefix pre- in \\\\\\', [' means…', 'After', 'Again', 'Before'], 2),
  q('en-4-060', 4, 'english', 'Past tense of lose:', ['Losed', 'Lost', 'Losen', 'Losing'], 1),
  q('en-4-061', 4, 'english', 'Homophone of \\\\\\', [':', 'Male', 'Mall', 'Mole'], 0),
  q('en-4-062', 4, 'english', '\\\\\\', [' — \\\\', ' modifies…', 'Singer (noun)', 'Talented (adjective)'], 1),
  q('en-4-063', 4, 'english', 'Choose conjunction: ___ she practised daily, she improved.', ['Although', 'Unless', 'Because', 'Yet'], 2),
  q('en-4-064', 4, 'english', 'Suffix -able means…', ['Without', 'Full of', 'Capable of', 'Before'], 2),
  q('en-4-065', 4, 'english', 'Past tense of ring:', ['Ringed', 'Rang', 'Rung', 'Ringing'], 1),
  q('en-4-066', 4, 'english', 'Homophone of \\\\\\', [':', 'Week', 'Wake', 'Walk'], 0),
  q('en-4-067', 4, 'english', '\\\\\\', [' — type of adverb for \\\\', '?', 'Time', 'Place'], 2),
  q('en-4-068', 4, 'english', 'Choose conjunction: She is tired ___ she works anyway.', ['but', 'because', 'and', 'or'], 0),
  q('en-4-069', 4, 'english', 'Prefix sub- in \\\\\\', [' means…', 'Above', 'Under', 'After'], 1),
  q('en-4-070', 4, 'english', 'Past tense of sing:', ['Singed', 'Sung', 'Sang', 'Singing'], 2),
  q('en-4-071', 4, 'english', 'Homophone of \\\\\\', [':', 'Mete', 'Meat', 'Met'], 1),
  q('en-4-072', 4, 'english', '\\\\\\', [' — \\\\', ' is an adverb of…', 'Manner', 'Place'], 3),
  q('en-4-073', 4, 'english', 'Choose conjunction: You must eat ___ you will be hungry.', ['although', 'if', 'or', 'but'], 2),
  q('en-4-074', 4, 'english', 'Suffix -less in \\\\\\', [' means…', 'Full of harm', 'Without harm', 'Before harm'], 1),
  q('en-4-075', 4, 'english', 'Past tense of win:', ['Winned', 'Won', 'Winned', 'Winning'], 1),
  q('en-4-076', 4, 'english', 'Homophone of \\\\\\', [':', 'Bee', 'Bay', 'By'], 0),
  q('en-4-077', 4, 'english', '\\\\\\', [' — \\\\', ' here is a/an…', 'Adjective', 'Noun'], 2),
  q('en-4-078', 4, 'english', 'Choose conjunction: She ate ___ she was full.', ['if', 'although', 'until', 'yet'], 2),
  q('en-4-079', 4, 'english', 'Prefix inter- in \\\\\\', [' means…', 'Within', 'Between/among', 'Against'], 1),
  q('en-4-080', 4, 'english', 'Past tense of catch:', ['Catched', 'Caught', 'Cought', 'Catching'], 1),
  q('en-4-081', 4, 'english', 'Homophone of \\\\\\', [':', 'Blew', 'Blow', 'Blur'], 0),
  q('en-4-082', 4, 'english', '\\\\\\', [' — \\\\', ' is adverb of…', 'Manner', 'Place'], 3),
  q('en-4-083', 4, 'english', 'Choose conjunction: She likes reading ___ writing.', ['or', 'because', 'if', 'since'], 0),
  q('en-4-084', 4, 'english', 'Suffix -ment changes…', ['Adjective to adverb', 'Verb to noun', 'Noun to verb', 'Noun to adjective'], 1),
  q('en-4-085', 4, 'english', 'Past tense of find:', ['Finded', 'Found', 'Fand', 'Finding'], 1),
  q('en-4-086', 4, 'english', 'Homophone of \\\\\\', [':', 'Bee', 'Bear', 'Beer'], 1),
  q('en-4-087', 4, 'english', '\\\\\\', [' — \\\\', ' is adverb of…', 'Manner', 'Time'], 2),
  q('en-4-088', 4, 'english', 'Choose conjunction: ___ he was sick, he went to school.', ['Because', 'Although', 'Since', 'As'], 1),
  q('en-4-089', 4, 'english', 'Prefix anti- means…', ['For', 'Before', 'Against', 'After'], 2),
  q('en-4-090', 4, 'english', 'Past tense of bite:', ['Bited', 'Bitten', 'Bit', 'Biting'], 2),
  q('en-4-091', 4, 'english', 'Homophone of \\\\\\', [':', 'Weight', 'Wail', 'Wet'], 0),
  q('en-4-092', 4, 'english', '\\\\\\', [' — adverb of manner…', 'quickly', 'she', 'answers'], 0),
  q('en-4-093', 4, 'english', "Choose conjunction: I'll stay ___ you want me to go.", ['if', 'unless', 'although', 'because'], 1),
  q('en-4-094', 4, 'english', 'Suffix -ous changes…', ['Adverb to verb', 'Noun/Adjective to adjective meaning ', '', 'Noun to adverb'], 1),
  q('en-4-095', 4, 'english', 'Past tense of fight:', ['Fighted', 'Fought', 'Foughten', 'Fighting'], 1),
  q('en-4-096', 4, 'english', 'Homophone of "their":', ['There/They are', 'The', 'Them', 'Then'], 0),
  q('en-4-097', 4, 'english', '\\\\\\\\', [' — \\\\\\\\', ' is adverb of…', 'Place', 'Manner'], 2),
  q('en-4-098', 4, 'english', 'Choose conjunction: She reads books ___ learns a lot.', ['but', 'and', 'or', 'if'], 1),
  q('en-4-099', 4, 'english', 'Prefix trans- in \\\\\\\\', [' means…', 'Against', 'Before', 'Across'], 2),
  q('en-4-100', 4, 'english', 'Past tense of spend:', ['Spended', 'Spent', 'Spen', 'Spending'], 1),

  // ── Grade 5 ──────────────────────────────────────────────────────────────
  q('en-5-001', 5, 'english', 'Passive: They clean the room. → The room ___ cleaned.', ['is', 'are', 'be', 'been'], 0),
  q('en-5-002', 5, 'english', 'Synonym of begin:', ['End', 'Start', 'Stop', 'Close'], 1),
  q('en-5-003', 5, 'english', '\\\\\\\\', [' introduces…', 'Contrast', 'Only time', 'Only place'], 0),
  q('en-5-004', 5, 'english', 'Choose correct: He has ___ finished.', ['already', 'yet', 'ago', 'last'], 0),
  q('en-5-005', 5, 'english', '\\\\\\\\', [' is a…', 'Metaphor', 'Simile', 'Irony'], 1),
  q('en-5-006', 5, 'english', 'Antonym of scarce:', ['Rare', 'Abundant', 'Few', 'Little'], 1),
  q('en-5-007', 5, 'english', 'Reported speech: He said, \\\\\\\\', [' → He said he ___ tired.', 'is', 'was', 'were'], 1),
  q('en-5-008', 5, 'english', 'A paragraph should usually have…', ['One main idea', 'No idea', 'Only jokes', 'Only numbers'], 0),
  q('en-5-009', 5, 'english', 'Suffix -ful in \\\\\\\\', [' means…', 'Without', 'Full of', 'Against'], 1),
  q('en-5-010', 5, 'english', 'Correct spelling:', ['Recieve', 'Receive', 'Receeve', 'Receve'], 1),
  q('en-5-011', 5, 'english', 'Passive: The cat ate the fish. → The fish ___ eaten by the cat.', ['is', 'was', 'were', 'be'], 1),
  q('en-5-012', 5, 'english', 'Synonym of difficult:', ['Easy', 'Simple', 'Hard', 'Soft'], 2),
  q('en-5-013', 5, 'english', '\\\\\\\\', [' can indicate…', 'Only place', 'Time or cause', 'Only manner'], 1),
  q('en-5-014', 5, 'english', 'Correct: She ___ not seen him yet.', ['have', 'has', 'had', 'was'], 1),
  q('en-5-015', 5, 'english', '\\\\\\\\', [' is a…', 'Simile', 'Metaphor', 'Irony'], 1),
  q('en-5-016', 5, 'english', 'Antonym of victory:', ['Win', 'Triumph', 'Defeat', 'Success'], 2),
  q('en-5-017', 5, 'english', 'Reported speech: She said, \\\\\\\\', [' → She said she ___ come.', 'will', 'would', 'shall'], 1),
  q('en-5-018', 5, 'english', 'The topic sentence is usually…', ['The last sentence', 'A random sentence', 'The first or main sentence of a paragraph', 'The shortest sentence'], 2),
  q('en-5-019', 5, 'english', 'Correct spelling:', ['Neccessary', 'Neccessery', 'Necessary', 'Necesary'], 2),
  q('en-5-020', 5, 'english', 'Passive: He built the house. → The house ___ built by him.', ['is', 'was', 'were', 'been'], 1),
  q('en-5-021', 5, 'english', 'Synonym of weary:', ['Energetic', 'Tired', 'Happy', 'Calm'], 1),
  q('en-5-022', 5, 'english', '\\\\\\\\', [' introduces…', 'Cause', 'Contrast', 'Time'], 1),
  q('en-5-023', 5, 'english', 'Correct: They ___ working since morning.', ['was', 'has been', 'have been', 'are'], 2),
  q('en-5-024', 5, 'english', '\\\\\\\\', [' is an example of…', 'Simile', 'Personification', 'Metaphor'], 1),
  q('en-5-025', 5, 'english', 'Antonym of ancient:', ['Old', 'Modern', 'Historic', 'Aged'], 1),
  q('en-5-026', 5, 'english', 'Reported speech: \\\\\\\\', [' he shouted. → He shouted at her to ___ away.', 'went', 'go', 'gone'], 1),
  q('en-5-027', 5, 'english', 'A supporting sentence adds…', ['The main point only', 'Details to support the topic', 'A new topic', 'Nothing'], 1),
  q('en-5-028', 5, 'english', 'Correct spelling:', ['Accomodate', 'Accommodate', 'Acommodate', 'Accommodat'], 1),
  q('en-5-029', 5, 'english', 'Passive: They will fix the car. → The car ___ fixed.', ['will be', 'is being', 'was being', 'had been'], 0),
  q('en-5-030', 5, 'english', 'Synonym of peculiar:', ['Normal', 'Strange', 'Common', 'Simple'], 1),
  q('en-5-031', 5, 'english', '\\\\\\\\', [' introduces…', 'Contrast', 'Condition', 'Time'], 1),
  q('en-5-032', 5, 'english', 'Correct: I ___ finished my homework.', ['has', 'have', 'had (present)', 'am'], 1),
  q('en-5-033', 5, 'english', '\\\\\\\\', [' is a…', 'Simile', 'Personification', 'Metaphor'], 2),
  q('en-5-034', 5, 'english', 'Antonym of generous:', ['Kind', 'Charitable', 'Selfish', 'Warm'], 2),
  q('en-5-035', 5, 'english', 'Reported speech: She asked, \\\\\\\\', [' → She asked if ___ ready.', 'I am', 'I was', 'I were'], 1),
  q('en-5-036', 5, 'english', 'A concluding sentence…', ['Introduces the topic', 'Adds details', 'Sums up the paragraph', 'Asks a question'], 2),
  q('en-5-037', 5, 'english', 'Correct spelling:', ['Independant', 'Independent', 'Independant', 'Independente'], 1),
  q('en-5-038', 5, 'english', 'Passive: The students cleaned the classroom. → The classroom ___ by the students.', ['is cleaned', 'was cleaned', 'were cleaned', 'been cleaned'], 1),
  q('en-5-039', 5, 'english', 'Synonym of intelligent:', ['Dull', 'Foolish', 'Clever', 'Slow'], 2),
  q('en-5-040', 5, 'english', '\\\\\\\\', [' introduces…', 'Contrast', 'Manner', 'Condition'], 2),
  q('en-5-041', 5, 'english', 'Correct: She ___ in Paris for three years.', ['live', 'lives', 'has lived', 'lived'], 2),
  q('en-5-042', 5, 'english', '\\\\\\\\', [' is an example of…', 'Simile', 'Personification', 'Metaphor'], 1),
  q('en-5-043', 5, 'english', 'Antonym of polite:', ['Courteous', 'Rude', 'Gentle', 'Kind'], 1),
  q('en-5-044', 5, 'english', 'Reported speech: \\\\\\\\', [' → She told him ___ it.', 'do', 'to do', 'doing'], 1),
  q(`en-5-045`, 5, `english`, `A paragraph\\'s coherence means…`, [`Sentences are unconnected`, `Ideas flow logically and are connected`, `Only long sentences`, `Only short sentences`], 1),
  q('en-5-046', 5, 'english', 'Correct spelling:', ['Suprise', 'Surprize', 'Surprise', 'Surprize'], 2),
  q('en-5-047', 5, 'english', 'Passive: Someone stole my bag. → My bag ___ stolen.', ['is', 'was', 'were', 'be'], 1),
  q('en-5-048', 5, 'english', 'Synonym of fragile:', ['Sturdy', 'Delicate', 'Strong', 'Tough'], 1),
  q('en-5-049', 5, 'english', '\\\\\\\\', [' shows…', 'Cause', 'Contrast/Concession', 'Time'], 1),
  q('en-5-050', 5, 'english', 'Correct: She ___ her keys.', ['lose', 'losted', 'has lost', 'lose'], 2),
  q('en-5-051', 5, 'english', '\\\\\\\\', [' is a…', 'Simile', 'Personification', 'Metaphor'], 2),
  q('en-5-052', 5, 'english', 'Antonym of transparent:', ['Clear', 'Opaque', 'Bright', 'Shiny'], 1),
  q('en-5-053', 5, 'english', "Reported speech: 'I don't know the answer.' → He said he ___ the answer.", ["don't know", "didn't know", 'will know', 'knows'], 1),
  q('en-5-054', 5, 'english', 'The purpose of a thesis statement is to…', ['End the essay', 'State the main argument or point', 'List facts', 'Begin a new topic'], 1),
  q('en-5-055', 5, 'english', 'Correct spelling:', ['Perseverence', 'Perserverance', 'Perseverance', 'Perserverence'], 2),
  q('en-5-056', 5, 'english', 'Passive: They will announce the results. → The results ___ announced.', ['is going to be', 'will be', 'were', 'was'], 1),
  q('en-5-057', 5, 'english', 'Synonym of obscure:', ['Clear', 'Famous', 'Unknown/unclear', 'Bright'], 2),
  q('en-5-058', 5, 'english', '\\\\\\\\', [' is used to show…', 'Cause', 'Contrast', 'Time'], 1),
  q('en-5-059', 5, 'english', 'Correct: He ___ here since 2020.', ['is', 'has been', 'was', 'were'], 1),
  q('en-5-060', 5, 'english', '\\\\\\\\', [' — sky has a human emotion. This is…', 'Simile', 'Metaphor', 'Personification'], 2),
  q('en-5-061', 5, 'english', 'Antonym of humble:', ['Modest', 'Arrogant', 'Gentle', 'Kind'], 1),
  q('en-5-062', 5, 'english', 'Reported speech: \\\\\\\\', [' → She asked him to ___ down.', 'sat', 'sit', 'sitting'], 1),
  q('en-5-063', 5, 'english', 'Cohesion in writing is achieved by using…', ['Random sentences', 'Connectives and pronouns for reference', 'Only facts', 'Only questions'], 1),
  q('en-5-064', 5, 'english', 'Correct spelling:', ['Privilege', 'Privelege', 'Priviledge', 'Previlege'], 0),
  q('en-5-065', 5, 'english', 'Passive: They are making the cake. → The cake ___ being made.', ['is', 'was', 'are', 'be'], 0),
  q('en-5-066', 5, 'english', 'Synonym of anxious:', ['Calm', 'Nervous', 'Happy', 'Content'], 1),
  q('en-5-067', 5, 'english', '\\\\\\\\', [' introduces…', 'Contrast', 'Cause', 'Purpose'], 2),
  q('en-5-068', 5, 'english', 'Correct: By the time we arrived, they ___ left.', ['have', 'has', 'had', 'were'], 2),
  q('en-5-069', 5, 'english', 'Irony occurs when…', ['You say exactly what you mean', 'You say the opposite of what you mean for effect', 'You use a simile', 'You repeat words'], 1),
  q('en-5-070', 5, 'english', 'Antonym of mandatory:', ['Compulsory', 'Required', 'Optional', 'Essential'], 2),
  q('en-5-071', 5, 'english', 'Reported speech: \\\\\\\\', [' → She said they ___ leaving the next day.', 'are', 'were', 'will be'], 1),
  q('en-5-072', 5, 'english', 'A body paragraph should begin with…', ['A random fact', 'A topic sentence', 'A conclusion', 'A question only'], 1),
  q('en-5-073', 5, 'english', 'Correct spelling:', ['Exaggerate', 'Exagerate', 'Exaggerete', 'Exaggarate'], 0),
  q('en-5-074', 5, 'english', 'Passive: She is writing the letter. → The letter ___ being written by her.', ['is', 'was', 'were', 'has'], 0),
  q('en-5-075', 5, 'english', 'Synonym of abundant:', ['Scarce', 'Plentiful', 'Empty', 'Rare'], 1),
  q('en-5-076', 5, 'english', '\\\\\\\\', [' introduces…', 'Contrast', 'Cause', 'Purpose'], 2),
  q('en-5-077', 5, 'english', 'Correct: She ___ for two hours before the show.', ['practised', 'had practised', 'practise', 'is practising'], 1),
  q('en-5-078', 5, 'english', 'Hyperbole is…', ['A comparison using \\\\', ' or \\\\', '', 'Extreme exaggeration for effect'], 1),
  q('en-5-079', 5, 'english', 'Antonym of vague:', ['Clear', 'Unclear', 'Hazy', 'Blurry'], 0),
  q('en-5-080', 5, 'english', 'Reported speech: \\\\\\\\', [' → She said she ___ finished.', 'has', 'have', 'had'], 2),
  q('en-5-081', 5, 'english', 'An effective introduction should…', ['End the discussion', 'Introduce the topic and engage the reader', 'List all facts', 'Ask only questions'], 1),
  q('en-5-082', 5, 'english', 'Correct spelling:', ['Occurrence', 'Ocurrence', 'Occurance', 'Occurence'], 0),
  q('en-5-083', 5, 'english', 'Passive: They had completed the project. → The project ___ been completed.', ['is', 'was', 'has', 'had'], 3),
  q('en-5-084', 5, 'english', 'Synonym of tranquil:', ['Busy', 'Noisy', 'Peaceful', 'Crowded'], 2),
  q('en-5-085', 5, 'english', '\\\\\\\\', [' introduces…', 'Cause', 'Contrast', 'Condition (negative)'], 2),
  q('en-5-086', 5, 'english', 'Correct: She ___ the answer when I asked.', ['know', 'knows', 'knew', 'known'], 2),
  q('en-5-087', 5, 'english', 'An alliteration is…', ['Repetition of end sounds', 'Repetition of initial consonant sounds', 'A comparison', 'An exaggeration'], 1),
  q('en-5-088', 5, 'english', 'Antonym of lenient:', ['Easy', 'Strict', 'Kind', 'Gentle'], 1),
  q('en-5-089', 5, 'english', "Reported speech: 'Don't touch that!' → She warned him ___ touch that.", ['to not', 'not to', 'no', 'never to ever'], 1),
  q('en-5-090', 5, 'english', 'A well-organised essay has…', ['Only a body', 'Introduction, body, and conclusion', 'Only a conclusion', 'No structure needed'], 1),
  q('en-5-091', 5, 'english', 'Correct spelling:', ['Mischievous', 'Mischevious', 'Mischeivous', 'Mischievious'], 0),
  q('en-5-092', 5, 'english', 'Passive: She took the picture. → The picture ___ taken by her.', ['is', 'was', 'were', 'be'], 1),
  q('en-5-093', 5, 'english', 'Synonym of durable:', ['Fragile', 'Long-lasting', 'Weak', 'Brittle'], 1),
  q('en-5-094', 5, 'english', '\\\\', [' introduces…', 'Cause', 'Contrast', 'Condition'], 3),
  q('en-5-095', 5, 'english', 'Correct: She ___ to that school since she was six.', ['go', 'goes', 'has gone', 'had been going'], 3),
  q('en-5-096', 5, 'english', 'Onomatopoeia is when…', ['Words sound like what they describe', 'Words are exaggerated', 'Words are compared', 'Words are repeated'], 0),
  q('en-5-097', 5, 'english', 'Antonym of hostile:', ['Aggressive', 'Friendly', 'Angry', 'Fierce'], 1),
  q('en-5-098', 5, 'english', 'Reported speech: \\\\', ['t been there.\\\\\\\\', ', [', 't', 'have not'], 2),
  q('en-5-099', 5, 'english', 'The conclusion of an essay should…', ['Begin a new topic', 'Summarise and restate main points', 'Only ask questions', 'List new facts'], 1),
  q('en-5-100', 5, 'english', 'Correct spelling:', ['Conscientiuos', 'Conscientious', 'Conscientous', 'Consciensious'], 1),

  // ── Grade 6 ──────────────────────────────────────────────────────────────
  q('en-6-001', 6, 'english', 'If it rains, we ___ stay indoors.', ['will', 'was', 'were', 'been'], 0),
  q('en-6-002', 6, 'english', '\\\\\\\\', [' is a…', 'Simile', 'Metaphor', 'Command'], 1),
  q('en-6-003', 6, 'english', 'Choose formal greeting for a letter:', ['Hey dude', 'Dear Sir/Madam', 'Yo', 'Sup'], 1),
  q('en-6-004', 6, 'english', 'Passive often focuses on…', ['Action receiver', 'Only spelling', 'Only rhyme', 'Only font'], 0),
  q('en-6-005', 6, 'english', 'Idiom: \\\\\\\\', [' means…', 'Very easy', 'Very hard', 'Very sweet only'], 0),
  q('en-6-006', 6, 'english', 'Relative pronoun: The girl ___ won is my sister.', ['which', 'who', 'where', 'when'], 1),
  q('en-6-007', 6, 'english', 'Tone of a persuasive text is often…', ['Convincing', 'Only sleepy', 'Only musical', 'Only numeric'], 0),
  q('en-6-008', 6, 'english', 'Correct: Neither of them ___ ready.', ['are', 'is', 'be', 'were always'], 1),
  q('en-6-009', 6, 'english', '\\\\\\\\', [' is a list of…', 'Sources', 'Sports scores', 'Colours'], 0),
  q('en-6-010', 6, 'english', 'Theme of a story means…', ['Central message', 'Page count', 'Cover price', 'Author age'], 0),
  q('en-6-011', 6, 'english', 'Idiom: \\\\\\\\', [' means…', 'Get injured', 'Good luck', 'Run fast'], 1),
  q('en-6-012', 6, 'english', 'Type 2 conditional: If I ___ rich, I would travel.', ['am', 'were', 'was', 'be'], 1),
  q('en-6-013', 6, 'english', 'A formal letter closes with:', ['See ya', 'Love you', 'Yours faithfully/sincerely', 'Bye bye'], 2),
  q('en-6-014', 6, 'english', 'Relative pronoun: The book ___ I read was great.', ['who', 'whose', 'which/that', 'when'], 2),
  q('en-6-015', 6, 'english', 'Mood in literature refers to…', ['The character\\\\', ', ', ', ', ', '], 1),
  q('en-6-016', 6, 'english', 'Correct: A number of students ___ absent.', ['is', 'are', 'was', 'were always'], 1),
  q('en-6-017', 6, 'english', '\\\\\\\\', [' writing deals with…', 'Concrete objects only', 'Ideas, concepts, emotions', 'Math problems'], 1),
  q('en-6-018', 6, 'english', 'Idiom: \\\\\\\\', [' means…', 'Carpentry', 'Be exactly right', 'Hammer something'], 1),
  q('en-6-019', 6, 'english', 'Type 3 conditional: If she ___ studied, she would have passed.', ['had', 'has', 'have', 'was'], 0),
  q('en-6-020', 6, 'english', "In formal writing, contractions like 'can't'…", ['Are preferred', 'Should be avoided', 'Must be used', 'Are irrelevant'], 1),
  q('en-6-021', 6, 'english', 'Relative pronoun: The house ___ they live is new.', ['which', 'who', 'where', 'that'], 2),
  q('en-6-022', 6, 'english', 'Tone of a satirical text is often…', ['Praising', 'Mocking/ironic', 'Boring', 'Purely factual'], 1),
  q('en-6-023', 6, 'english', 'Correct: The committee ___ reached a decision.', ['have', 'has', 'are', 'were'], 1),
  q('en-6-024', 6, 'english', '\\\\', [' in rhetoric means…', 'Repetition at the end of sentences', 'Repetition at the beginning of clauses', 'A figure of speech using comparison'], 1),
  q('en-6-025', 6, 'english', 'Idiom: \\\\', [' means…', 'During full moon only', 'Very rarely', 'Every month'], 1),
  q('en-6-026', 6, 'english', 'Type 1 conditional: If she studies hard, she ___ pass.', ['would', 'will', 'had', 'has'], 1),
  q('en-6-027', 6, 'english', 'Relative pronoun: The man ___ car was stolen called the police.', ['who', 'whom', 'whose', 'which'], 2),
  q('en-6-028', 6, 'english', 'In academic writing, the first-person \\\\', [' is…', 'Always required', 'Generally avoided in formal essays', 'Compulsory'], 1),
  q('en-6-029', 6, 'english', 'Correct: Neither the teacher nor the students ___ ready.', ['was', 'is', 'are', 'be'], 2),
  q('en-6-030', 6, 'english', 'A narrative essay primarily…', ['Argues a point', 'Tells a story', 'Describes an object', 'Lists instructions'], 1),
  q('en-6-031', 6, 'english', 'Idiom: \\\\', [' means…', 'Cook beans', 'Reveal a secret', 'Make a mess'], 1),
  q('en-6-032', 6, 'english', 'Zero conditional: If you heat water to 100°C, it ___.', ['would boil', 'boils', 'boiled', 'had boiled'], 1),
  q('en-6-033', 6, 'english', "Relative pronoun: That's the reason ___ she left.", ['which', 'who', 'why', 'whom'], 2),
  q('en-6-034', 6, 'english', '"Ethos" in persuasion refers to…', ['Logic and facts', 'Emotion', "The speaker's credibility", 'Style of writing'], 2),
  q('en-6-035', 6, 'english', 'Correct: Each of the boys ___ done his homework.', ['have', 'has', 'are', 'were'], 1),
  q('en-6-036', 6, 'english', 'An expository essay primarily…', ['Tells a story', 'Expresses emotions only', 'Explains or informs', 'Argues only with opinions'], 2),
  q('en-6-037', 6, 'english', 'Idiom: \\\\\\\\', [' means…', 'Outdoor activity', 'Feeling unwell', 'Rainy day'], 1),
  q('en-6-038', 6, 'english', 'Type 2 conditional result clause uses…', ['will + verb', 'would + verb', 'shall + verb', 'might always'], 1),
  q('en-6-039', 6, 'english', 'Relative pronoun: The woman ___ I spoke to was kind.', ['who', 'whom', 'which', 'whose'], 1),
  q('en-6-040', 6, 'english', '"Logos" in persuasion refers to…', ["Speaker's character", 'Emotion of audience', 'Logic and evidence', 'Style of writing'], 2),
  q('en-6-041', 6, 'english', 'Correct: The news ___ shocking.', ['were', 'are', 'is', 'be'], 2),
  q('en-6-042', 6, 'english', 'A descriptive essay aims to…', ['Argue a position', 'Tell a story only', 'Paint a vivid picture with words', 'Explain a process'], 2),
  q('en-6-043', 6, 'english', 'Idiom: \\\\\\\\', [' means…', 'Eat metal', 'Endure pain bravely', 'Give up'], 1),
  q('en-6-044', 6, 'english', 'Type 3 conditional: She would have won ___ she had tried harder.', ['if', 'unless', 'although', 'since'], 0),
  q('en-6-045', 6, 'english', 'Relative pronoun: The time ___ we met was magical.', ['who', 'whom', 'which', 'when'], 3),
  q('en-6-046', 6, 'english', '"Pathos" in persuasion refers to…', ["Speaker's credibility", 'Emotional appeal', 'Logic and reasoning', 'Writing style'], 2),
  q('en-6-047', 6, 'english', 'Correct: Neither she nor they ___ aware of the problem.', ['was', 'is', 'are', 'be'], 2),
  q(`en-6-048`, 6, `english`, `In a persuasive essay, a counterargument is presented to…`, [`Weaken the essay`, `Show the writer\\'s weakness`, `Acknowledge and then refute opposing views`, `End the essay`], 2),
  q('en-6-049', 6, 'english', 'Idiom: \\\\\\\\', [' means…', 'Release a cat', 'Reveal a secret accidentally', 'Be careless'], 1),
  q('en-6-050', 6, 'english', 'Mixed conditional (present result of past): If she ___ trained, she would be fit now.', ['trains', 'had trained', 'would train', 'has trained'], 1),
  q('en-6-051', 6, 'english', 'Relative pronoun: The city ___ she was born is beautiful.', ['that', 'who', 'where', 'when'], 2),
  q(`en-6-052`, 6, `english`, `The purpose of a thesis in an argumentative essay is to…`, [`End the essay`, `State the writer\\'s central claim`, `Summarise only`, `List examples`], 1),
  q('en-6-053', 6, 'english', 'Correct: Either he or she ___ responsible.', ['are', 'is', 'am', 'be'], 1),
  q('en-6-054', 6, 'english', 'Idiom: \\\\\\\\', [' means…', 'Setting things on fire', 'Working/studying late', 'Cooking at midnight'], 1),
  q('en-6-055', 6, 'english', '\\\\\\\\', [' is…', 'Repetition at the start of clauses', 'Repetition at the end of clauses', 'A type of simile'], 1),
  q('en-6-056', 6, 'english', 'Correct: The data ___ clear.', ['were', 'are', 'is', 'be'], 2),
  q('en-6-057', 6, 'english', 'A process essay explains…', ['What something looks like', 'How to do something step by step', 'Why something happened', 'Who did something'], 1),
  q('en-6-058', 6, 'english', 'Idiom: \\\\\\\\', [' means…', 'Damage books', 'Study', 'Throw books'], 1),
  q(`en-6-059`, 6, `english`, `Type 1 conditional: ___ she calls, tell her I\\'m busy.`, [`Whether`, `If`, `Unless`, `Until`], 1),
  q('en-6-060', 6, 'english', 'Relative pronoun (non-restrictive): My sister, ___ is a doctor, lives in Paris.', ['that', 'which', 'who', 'whom'], 2),
  q('en-6-061', 6, 'english', 'In academic writing, evidence should be…', ['Invented', 'Cited and referenced properly', 'Guessed', 'Anecdotal only'], 1),
  q('en-6-062', 6, 'english', 'Correct: A pair of shoes ___ on the floor.', ['are', 'is', 'were', 'be'], 1),
  q('en-6-063', 6, 'english', '"The ball is in your court" means…', ['Play tennis', "It's your turn to decide", 'Go to court', 'Play a sport'], 1),
  q('en-6-064', 6, 'english', '\\\\\\\\', [' is a rhetorical device where…', 'Words are repeated at the start', 'The structure of phrases is reversed', 'Ideas are compared'], 1),
  q('en-6-065', 6, 'english', 'Correct: More than one student ___ absent.', ['were', 'are', 'is', 'be'], 2),
  q('en-6-066', 6, 'english', 'A cause and effect essay…', ['Tells a story', 'Explores why things happen and their results', 'Argues for a single point', 'Describes only'], 1),
  q('en-6-067', 6, 'english', 'Idiom: \\\\\\\\', [' means…', 'Injury', 'Very expensive', 'Worth every cent'], 1),
  q('en-6-068', 6, 'english', 'Conditional: ___ she practised more, she would have improved.', ['If', 'Had', 'Unless', 'Whether'], 1),
  q('en-6-069', 6, 'english', 'Relative pronoun: Do you know the reason ___ he left?', ['when', 'where', 'which', 'why'], 3),
  q('en-6-070', 6, 'english', 'In writing, \\\\\\\\', [' refers to…', 'Sentence length', 'Word choice', 'Paragraph structure'], 1),
  q('en-6-071', 6, 'english', 'Correct: The majority ___ in favour of the plan.', ['is', 'are', 'was only', 'be'], 1),
  q('en-6-072', 6, 'english', 'A comparison essay…', ['Only praises one subject', 'Examines similarities and/or differences', 'Only narrates', 'Only describes'], 1),
  q('en-6-073', 6, 'english', 'Idiom: \\\\\\\\', [' means…', 'Animals falling', 'Raining heavily', 'Noisy weather'], 1),
  q('en-6-074', 6, 'english', 'Type 2 conditional: I wish I ___ taller.', ['am', 'were', 'will be', 'be'], 1),
  q('en-6-075', 6, 'english', 'Relative pronoun: This is the school ___ I studied.', ['who', 'whom', 'which/where', 'when'], 2),
  q('en-6-076', 6, 'english', 'In formal writing, \\\\\\\\', [' is…', 'Always preferred', 'Better replaced with full examples or omitted', 'Required'], 1),
  q('en-6-077', 6, 'english', 'Correct: Everyone ___ given a chance to speak.', ['were', 'are', 'was', 'be'], 2),
  q(`en-6-078`, 6, `english`, `A reflective essay…`, [`Only argues`, `Explores the writer\\'s personal experience and growth`, `Lists instructions`, `Summarises only`], 1),
  q('en-6-079', 6, 'english', '"A blessing in disguise" means…', ['Something evil', "Something good that didn't seem so at first", 'A hidden gift', 'Bad luck'], 1),
  q('en-6-080', 6, 'english', 'Zero conditional: Water freezes ___ the temperature drops to 0°C.', ['would', 'when/if', 'had', 'should'], 1),
  q('en-6-081', 6, 'english', 'Relative pronoun: That was the year ___ they moved.', ['who', 'which', 'where', 'when'], 3),
  q('en-6-082', 6, 'english', 'In writing, \\\\\\\\', [' refers to…', 'Word choice', 'Sentence structure and arrangement', 'Tone'], 1),
  q('en-6-083', 6, 'english', 'Correct: The staff ___ divided in their opinions.', ['is', 'are', 'was only', 'be'], 1),
  q('en-6-084', 6, 'english', 'Idiom: \\\\\\\\', [' means…', 'The whole problem', 'A small visible part of a larger issue', 'Cold weather'], 1),
  q('en-6-085', 6, 'english', 'Type 3 conditional structure:', ['If + past simple, would + base', 'If + past perfect, would have + past participle', 'If + present, will + base', 'If + perfect, would + base'], 1),
  q('en-6-086', 6, 'english', 'Relative pronoun: The moment ___ I realised was crucial.', ['who', 'which', 'where', 'when'], 3),
  q('en-6-087', 6, 'english', 'In persuasive writing, \\\\\\\\', [' means…', 'Giving up your argument', 'Acknowledging the other side before refuting it', 'Only agreeing'], 1),
  q('en-6-088', 6, 'english', 'Correct: No news ___ good news.', ['are', 'is', 'were', 'be'], 1),
  q('en-6-089', 6, 'english', 'Idiom: \\\\\\\\', [' means…', 'Playing a board game', 'Starting all over from the beginning', 'Returning home'], 1),
  q(`en-6-090`, 6, `english`, `Mixed conditional (past action, present result): If I ___ listened, I\\'d know the answer now.`, [`listen`, `had listened`, `would listen`, `have listened`], 1),
  q('en-6-091', 6, 'english', 'Relative pronoun: The company ___ he works for is famous.', ['who', 'whom', 'that/which', 'where'], 2),
  q('en-6-092', 6, 'english', '"Stream of consciousness" in literature…', ['Describes a river', "Records a character's continuous flow of thoughts", 'Is a poetry style', 'Describes nature'], 1),
  q('en-6-093', 6, 'english', 'Correct: Either the students or the teacher ___ to blame.', ['is', 'are', 'am', 'be'], 0),
  q('en-6-094', 6, 'english', 'Idiom: \\\\\\\\', [' means…', 'Shouting is good', 'What you do matters more than what you say', 'Be quiet'], 1),
  q('en-6-095', 6, 'english', 'An argumentative essay should be supported by…', ['Opinions only', 'Evidence, examples, and logical reasoning', 'Emotions only', 'Anecdotes only'], 1),
  q('en-6-096', 6, 'english', 'Correct: The news ___ spread quickly.', ['were', 'are', 'has', 'have'], 2),
  q('en-6-097', 6, 'english', '"Voice" in writing refers to…', ['How loud you speak', "The writer's unique personality and style in text", 'Only dialogue', 'Grammar choice'], 1),
  q('en-6-098', 6, 'english', 'Idiom: \\\\\\\\', [' means…', 'Eat too much food', 'Take on more than you can handle', 'Be greedy with food'], 1),
  q('en-6-099', 6, 'english', 'Type 1 conditional: She will fail the test if she ___ study.', ['don\\\\', ', ', 't', 'doesn\\\\'], 2),
  q('en-6-100', 6, 'english', 'In literary analysis, \\\\\\\\', [' means…', 'Skimming the text quickly', 'Analysing specific details of the text carefully', 'Reading only the summary'], 1),
];
