import { q, type Question } from './types';

export const MALAY_QUESTIONS: Question[] = [
  // ── Grade 1 ──────────────────────────────────────────────────────────────
  q('ms-1-001', 1, 'malay', '\\\\\\\\', [' bermaksud?', 'Kamu', 'Saya', 'Mereka'], 1),
  q('ms-1-002', 1, 'malay', 'Warna langit biasanya?', ['Merah', 'Biru', 'Hitam', 'Kuning'], 1),
  q('ms-1-003', 1, 'malay', 'Haiwan yang mengeong?', ['Lembu', 'Kucing', 'Itik', 'Ikan'], 1),
  q('ms-1-004', 1, 'malay', '\\\\\\\\', [' digunakan untuk?', 'Mengucapkan rasa syukur', 'Marah', 'Tidur'], 0),
  q('ms-1-005', 1, 'malay', 'Buah kuning yang melengkung?', ['Epal', 'Pisang', 'Anggur', 'Durian'], 1),
  q('ms-1-006', 1, 'malay', 'Lawannya \\\\\\\\', [':', 'Kecil', 'Panjang', 'Tinggi'], 0),
  q('ms-1-007', 1, 'malay', 'Kita menulis dengan?', ['Sudu', 'Pensel', 'Bola', 'Stokin'], 1),
  q('ms-1-008', 1, 'malay', '\\\\\\\\', [' ialah?', 'Ucapan', 'Nama buah', 'Nombor'], 0),
  q('ms-1-009', 1, 'malay', 'Berapa kaki seekor ayam?', ['1', '2', '4', '6'], 1),
  q('ms-1-010', 1, 'malay', 'Air diminum untuk?', ['Menghilangkan haus', 'Terbang', 'Membaca', 'Melukis'], 0),
  q('ms-1-011', 1, 'malay', 'Warna daun yang sihat?', ['Merah', 'Biru', 'Hijau', 'Kuning'], 2),
  q('ms-1-012', 1, 'malay', 'Haiwan yang bertelur?', ['Kucing', 'Kambing', 'Ayam', 'Lembu'], 2),
  q('ms-1-013', 1, 'malay', 'Lawannya \\\\\\\\', ['?', 'Tinggi', 'Besar', 'Pendek'], 2),
  q('ms-1-014', 1, 'malay', '\\\\\\\\', [' diucapkan?', 'Waktu pagi', 'Waktu tengahari', 'Waktu malam'], 2),
  q('ms-1-015', 1, 'malay', 'Kita melihat menggunakan?', ['Telinga', 'Hidung', 'Mulut', 'Mata'], 3),
  q('ms-1-016', 1, 'malay', 'Haiwan berbunyi \\\\\\\\', ['?', 'Kambing', 'Lembu', 'Kuda'], 1),
  q('ms-1-017', 1, 'malay', 'Sayur berwarna oren?', ['Bayam', 'Lobak merah', 'Kobis', 'Timun'], 1),
  q('ms-1-018', 1, 'malay', 'Lawannya \\\\\\\\', ['?', 'Tengah', 'Tepi', 'Bawah'], 2),
  q('ms-1-019', 1, 'malay', '\\\\\\\\', [' digunakan bila?', 'Gembira', 'Tersilap atau meminta ampun', 'Lapar'], 1),
  q('ms-1-020', 1, 'malay', 'Berapa bulan dalam setahun?', ['10', '11', '12', '13'], 2),
  q('ms-1-021', 1, 'malay', 'Kita mendengar menggunakan?', ['Mata', 'Telinga', 'Hidung', 'Kaki'], 1),
  q('ms-1-022', 1, 'malay', 'Haiwan yang boleh terbang?', ['Ikan', 'Burung', 'Lembu', 'Katak'], 1),
  q('ms-1-023', 1, 'malay', 'Lawannya \\\\\\\\', ['?', 'Besar', 'Kecil', 'Pendek/rendah'], 2),
  q('ms-1-024', 1, 'malay', '\\\\\\\\', [' bermaksud?', 'Terima kasih', 'Maaf', 'Minta bantuan'], 2),
  q('ms-1-025', 1, 'malay', 'Matahari terbit di?', ['Barat', 'Utara', 'Timur', 'Selatan'], 2),
  q('ms-1-026', 1, 'malay', 'Berapa hari dalam seminggu?', ['5', '6', '7', '8'], 2),
  q('ms-1-027', 1, 'malay', 'Haiwan yang berbunyi \\\\\\\\', ['?', 'Lembu', 'Kambing/biri-biri', 'Kuda'], 1),
  q('ms-1-028', 1, 'malay', 'Kita menggunakan hidung untuk?', ['Mendengar', 'Menghidu/mencium bau', 'Melihat', 'Merasai'], 1),
  q('ms-1-029', 1, 'malay', 'Lawannya \\\\\\\\', ['?', 'Panas', 'Terang', 'Basah'], 1),
  q('ms-1-030', 1, 'malay', '\\\\\\\\', [' bermaksud?', 'Jaga diri', 'Sampai jumpa', 'Ucapan kepada tetamu'], 2),
  q('ms-1-031', 1, 'malay', 'Baju dipakai di?', ['Kaki', 'Kepala', 'Badan', 'Tangan'], 2),
  q('ms-1-032', 1, 'malay', 'Berapa sisi sebuah segi tiga?', ['2', '3', '4', '5'], 1),
  q('ms-1-033', 1, 'malay', 'Haiwan yang hidup di air?', ['Kucing', 'Kuda', 'Ikan', 'Arnab'], 2),
  q('ms-1-034', 1, 'malay', 'Lawannya \\\\\\\\', ['?', 'Basah', 'Bersih', 'Kering'], 1),
  q('ms-1-035', 1, 'malay', '\\\\\\\\', [' diucapkan bila?', 'Semasa bertemu', 'Semasa perpisahan', 'Semasa makan'], 1),
  q('ms-1-036', 1, 'malay', 'Buah berwarna merah yang bulat?', ['Pisang', 'Betik', 'Epal', 'Durian'], 2),
  q('ms-1-037', 1, 'malay', 'Lawannya \\\\\\\\', ['?', 'Besar', 'Kuat', 'Lambat/perlahan'], 2),
  q('ms-1-038', 1, 'malay', 'Kita tidur di?', ['Dapur', 'Bilik mandi', 'Bilik tidur', 'Taman'], 2),
  q('ms-1-039', 1, 'malay', 'Haiwan yang mempunyai leher panjang?', ['Kuda', 'Zirafah', 'Kucing', 'Ikan'], 1),
  q('ms-1-040', 1, 'malay', '\\\\\\\\', [' ialah?', 'Bahasa Melayu formal untuk ucapan salam', 'Nama makanan', 'Nombor'], 0),
  q('ms-1-041', 1, 'malay', 'Lawannya \\\\\\\\', ['?', 'Kecil', 'Pendek', 'Tua'], 2),
  q('ms-1-042', 1, 'malay', 'Kita membaca?', ['Buku', 'Kasut', 'Pinggan', 'Bola'], 0),
  q('ms-1-043', 1, 'malay', 'Haiwan yang menghasilkan madu?', ['Kupu-kupu', 'Lebah', 'Semut', 'Nyamuk'], 1),
  q('ms-1-044', 1, 'malay', 'Lawannya \\\\\\\\', ['?', 'Kecil', 'Ringan', 'Perlahan'], 1),
  q('ms-1-045', 1, 'malay', 'Apabila hujan, kita menggunakan?', ['Topi', 'Kasut', 'Payung', 'Seluar'], 2),
  q('ms-1-046', 1, 'malay', 'Berapa huruf vokal dalam Bahasa Melayu?', ['3', '4', '5', '6'], 2),
  q('ms-1-047', 1, 'malay', 'Haiwan yang hidup di darat dan air?', ['Kucing', 'Katak', 'Ikan', 'Burung'], 1),
  q('ms-1-048', 1, 'malay', 'Lawannya \\\\\\\\', ['?', 'Naik', 'Turun', 'Keluar'], 2),
  q('ms-1-049', 1, 'malay', 'Kita memasak di?', ['Bilik tidur', 'Bilik mandi', 'Dapur', 'Taman'], 2),
  q('ms-1-050', 1, 'malay', 'Warna matahari pada siang hari?', ['Biru', 'Merah', 'Kuning/jingga terang', 'Hijau'], 2),
  q('ms-1-051', 1, 'malay', 'Lawannya \\\\\\\\', ['?', 'Basah', 'Kering', 'Sejuk'], 2),
  q('ms-1-052', 1, 'malay', 'Kita mandi di?', ['Dapur', 'Bilik tidur', 'Bilik mandi', 'Taman'], 2),
  q('ms-1-053', 1, 'malay', 'Haiwan yang terbesar?', ['Tikus', 'Kucing', 'Gajah', 'Arnab'], 2),
  q('ms-1-054', 1, 'malay', 'Lawannya \\\\\\\\', ['?', 'Atas', 'Bawah', 'Tepi'], 3),
  q('ms-1-055', 1, 'malay', 'Ibu bapa kita ialah?', ['Adik beradik', 'Guru', 'Ayah dan ibu', 'Jiran'], 2),
  q('ms-1-056', 1, 'malay', 'Lawannya \\\\\\\\', ['?', 'Licin', 'Keras', 'Ringan'], 1),
  q('ms-1-057', 1, 'malay', 'Kita pergi ke sekolah untuk?', ['Tidur', 'Belajar', 'Bermain sahaja', 'Makan sahaja'], 1),
  q('ms-1-058', 1, 'malay', 'Haiwan berbunyi \\\\\\\\', ['?', 'Ayam', 'Itik', 'Kambing'], 1),
  q('ms-1-059', 1, 'malay', 'Lawannya \\\\\\\\', ['?', 'Pedas', 'Pahit/masam', 'Masin'], 1),
  q('ms-1-060', 1, 'malay', 'Tumbuhan memerlukan apa untuk hidup?', ['Pasir dan batu', 'Cahaya matahari dan air', 'Ais dan api', 'Mainan'], 1),
  q('ms-1-061', 1, 'malay', 'Kita menggunakan lidah untuk?', ['Mendengar', 'Melihat', 'Menghidu', 'Merasa'], 3),
  q('ms-1-062', 1, 'malay', 'Haiwan yang hidup di padang rumput?', ['Ikan', 'Paus', 'Kuda', 'Sotong'], 2),
  q('ms-1-063', 1, 'malay', 'Lawannya \\\\\\\\', ['?', 'Mudah', 'Susah/sukar', 'Cepat'], 1),
  q('ms-1-064', 1, 'malay', 'Buah-buahan yang manis contohnya?', ['Lemon', 'Cili', 'Mangga masak', 'Belimbing muda'], 2),
  q('ms-1-065', 1, 'malay', 'Kita menggunakan tangan untuk?', ['Mendengar', 'Menghidu', 'Memegang/melakukan kerja', 'Melihat'], 2),
  q('ms-1-066', 1, 'malay', 'Lawannya \\\\\\\\', ['?', 'Kuat', 'Sihat', 'Miskin'], 2),
  q('ms-1-067', 1, 'malay', 'Semasa makan, kita menggunakan?', ['Pensel', 'Sudu dan garpu', 'Penggaris', 'Berus'], 1),
  q('ms-1-068', 1, 'malay', 'Haiwan yang berbunyi \\\\\\\\', ['?', 'Kucing', 'Anjing', 'Lembu'], 1),
  q('ms-1-069', 1, 'malay', 'Lawannya \\\\\\\\', ['?', 'Kurang', 'Sikit', 'Tiada'], 2),
  q('ms-1-070', 1, 'malay', 'Nombor selepas 4 ialah?', ['3', '5', '6', '7'], 1),
  q('ms-1-071', 1, 'malay', 'Kita membersihkan gigi menggunakan?', ['Sabun', 'Sikat gigi dan ubat gigi', 'Air sahaja', 'Kain'], 1),
  q('ms-1-072', 1, 'malay', 'Haiwan yang menyusukan anak?', ['Ikan', 'Burung', 'Kucing/mamalia', 'Katak'], 2),
  q('ms-1-073', 1, 'malay', 'Lawannya \\\\\\\\', ['?', 'Panas', 'Basah', 'Sejuk'], 1),
  q('ms-1-074', 1, 'malay', 'Tempat kita pergi untuk berubat?', ['Sekolah', 'Pasar', 'Hospital/klinik', 'Taman'], 2),
  q('ms-1-075', 1, 'malay', 'Nombor sebelum 10 ialah?', ['8', '9', '11', '7'], 1),
  q('ms-1-076', 1, 'malay', 'Kita memakai kasut di?', ['Tangan', 'Kepala', 'Kaki', 'Bahu'], 2),
  q('ms-1-077', 1, 'malay', 'Haiwan yang mempunyai sirip?', ['Arnab', 'Kucing', 'Ikan', 'Burung'], 2),
  q('ms-1-078', 1, 'malay', 'Lawannya \\\\\\\\', ['?', 'Petang', 'Pagi', 'Malam'], 2),
  q('ms-1-079', 1, 'malay', 'Kita menggunakan lampu untuk?', ['Makan', 'Tidur', 'Menerangi kawasan gelap', 'Bermain'], 2),
  q('ms-1-080', 1, 'malay', 'Berapa sudut pada sebuah segi empat?', ['2', '3', '4', '5'], 2),
  q('ms-1-081', 1, 'malay', 'Buah yang bewarna kuning cerah dan panjang?', ['Epal', 'Pisang', 'Mangga', 'Limau'], 1),
  q('ms-1-082', 1, 'malay', 'Lawannya \\\\\\\\', ['?', 'Rendah', 'Lemah', 'Kecil'], 1),
  q('ms-1-083', 1, 'malay', 'Kita menggunakan payung semasa?', ['Panas terik sahaja', 'Hujan atau panas terik', 'Malam sahaja', 'Tidur'], 1),
  q('ms-1-084', 1, 'malay', 'Haiwan yang paling kecil antara ini?', ['Gajah', 'Kuda', 'Tikus', 'Lembu'], 2),
  q('ms-1-085', 1, 'malay', 'Lawannya \\\\\\\\', ['?', 'Masuk', 'Keluar', 'Tutup'], 2),
  q('ms-1-086', 1, 'malay', 'Tempat kita meminjam buku?', ['Hospital', 'Perpustakaan', 'Pasar raya', 'Stesen minyak'], 1),
  q('ms-1-087', 1, 'malay', 'Haiwan yang mempunyai bulu pelepah?', ['Ikan', 'Arnab', 'Burung', 'Ular'], 2),
  q('ms-1-088', 1, 'malay', 'Lawannya \\\\\\\\', ['?', 'Pergi', 'Datang', 'Turun'], 2),
  q('ms-1-089', 1, 'malay', 'Kita menjaga gigi dengan cara?', ['Makan banyak gula', 'Berus gigi setiap hari', 'Tidak minum air', 'Tidur awal'], 1),
  q('ms-1-090', 1, 'malay', 'Warna apa yang ada pada bendera Malaysia?', ['Hitam dan putih sahaja', 'Merah, putih, biru, dan kuning', 'Hijau dan merah sahaja', 'Biru dan kuning sahaja'], 1),
  q('ms-1-091', 1, 'malay', 'Haiwan yang hidup di dalam tanah?', ['Burung', 'Ikan', 'Cacing', 'Kucing'], 2),
  q('ms-1-092', 1, 'malay', 'Lawannya \\\\\\\\', ['?', 'Naik', 'Jalan', 'Keluar'], 2),
  q('ms-1-093', 1, 'malay', 'Kita pergi ke masjid untuk?', ['Membeli-belah', 'Bersembahyang/beribadah', 'Menonton wayang', 'Bermain'], 1),
  q('ms-1-094', 1, 'malay', 'Nombor terbesar antara 3, 7, 5, 1?', ['3', '5', '7', '1'], 2),
  q('ms-1-095', 1, 'malay', 'Haiwan yang menghasilkan susu?', ['Ayam', 'Ikan', 'Lembu', 'Arnab'], 2),
  q('ms-1-096', 1, 'malay', 'Lawannya \\\\\\\\', ['?', 'Pendek', 'Kurus', 'Rendah'], 1),
  q('ms-1-097', 1, 'malay', 'Kita makan dengan menggunakan?', ['Pensel', 'Sudu/garpu atau tangan', 'Penggaris', 'Gam'], 1),
  q('ms-1-098', 1, 'malay', 'Bunga kebangsaan Malaysia ialah?', ['Ros', 'Orkid', 'Bunga raya', 'Melur'], 2),
  q('ms-1-099', 1, 'malay', 'Lawannya \\\\\\\\', ['?', 'Sepi', 'Sunyi', 'Bising'], 2),
  q('ms-1-100', 1, 'malay', 'Kita mengucap \\\\\\\\', [' bila?', 'Hari seseorang lahir setiap tahun', 'Hari seseorang menangis', 'Hari seseorang tidur'], 0),

  // ── Grade 2 ──────────────────────────────────────────────────────────────
  q('ms-2-001', 2, 'malay', 'Jamak bagi \\\\\\\\', [':', 'Buku-buku', 'Bukus', 'Bukues'], 0),
  q('ms-2-002', 2, 'malay', '\\\\\\\\', [' merujuk kepada?', 'Saya', 'Orang ketiga', 'Nombor'], 1),
  q('ms-2-003', 2, 'malay', 'Lawannya \\\\\\\\', [':', 'Sejuk', 'Besar', 'Cepat'], 0),
  q('ms-2-004', 2, 'malay', 'Hari selepas Isnin?', ['Ahad', 'Selasa', 'Jumaat', 'Sabtu'], 1),
  q('ms-2-005', 2, 'malay', 'Anak anjing dipanggil?', ['Anak kucing', 'Anak anjing', 'Anak ayam', 'Anak lembu'], 1),
  q('ms-2-006', 2, 'malay', 'Balasan \\\\\\\\', [':', 'Sama-sama', 'Tolong', 'Bye'], 0),
  q('ms-2-007', 2, 'malay', 'Tempat tidur biasanya di?', ['Dapur', 'Bilik tidur', 'Taman', 'Jalan'], 1),
  q('ms-2-008', 2, 'malay', 'Pilih kata nama:', ['Lari', 'Cantik', 'Guru', 'Cepat'], 2),
  q('ms-2-009', 2, 'malay', 'Saya ___ ke sekolah.', ['pergi', 'pergis', 'pergian', 'pergi-pergi'], 0),
  q('ms-2-010', 2, 'malay', 'Yang manakah warna?', ['Gembira', 'Kuning', 'Lompat', 'Lembut'], 1),
  q('ms-2-011', 2, 'malay', 'Jamak bagi \\\\\\\\', [':', 'Murid-murid', 'Murids', 'Murides'], 0),
  q('ms-2-012', 2, 'malay', '\\\\\\\\', [' bermaksud?', 'Kamu', 'Saya sahaja', 'Kami (tidak termasuk pendengar)'], 2),
  q('ms-2-013', 2, 'malay', 'Lawannya \\\\\\\\', ['?', 'Gemuk', 'Besar', 'Pendek'], 1),
  q('ms-2-014', 2, 'malay', 'Hari selepas Rabu?', ['Selasa', 'Isnin', 'Khamis', 'Jumaat'], 2),
  q('ms-2-015', 2, 'malay', 'Anak ayam dipanggil?', ['Anak kucing', 'Anak lembu', 'Anak ayam', 'Anak kambing'], 2),
  q('ms-2-016', 2, 'malay', 'Kita pergi ke pasar untuk?', ['Belajar', 'Berubat', 'Membeli barang keperluan', 'Bersembahyang'], 2),
  q('ms-2-017', 2, 'malay', 'Pilih kata kerja:', ['Buku', 'Meja', 'Berlari', 'Manis'], 2),
  q('ms-2-018', 2, 'malay', 'Dia ___ seorang pelajar.', ['am', 'is', 'ialah/adalah', 'are'], 2),
  q('ms-2-019', 2, 'malay', 'Yang manakah bentuk?', ['Merah', 'Bulat', 'Lari', 'Manis'], 1),
  q('ms-2-020', 2, 'malay', 'Jamak bagi \\\\\\\\', [':', 'Pokok-pokok', 'Pooks', 'Pooky'], 0),
  q('ms-2-021', 2, 'malay', '\\\\\\\\', [' bermaksud?', 'Saya', 'Awak/engkau', 'Dia'], 1),
  q('ms-2-022', 2, 'malay', 'Lawannya \\\\\\\\', ['?', 'Sejuk', 'Terang', 'Basah'], 1),
  q('ms-2-023', 2, 'malay', 'Hari selepas Khamis?', ['Selasa', 'Rabu', 'Sabtu', 'Jumaat'], 3),
  q('ms-2-024', 2, 'malay', 'Anak lembu dipanggil?', ['Anak kambing', 'Anak kuda', 'Anak lembu', 'Anak anjing'], 2),
  q('ms-2-025', 2, 'malay', 'Kita pergi ke hospital untuk?', ['Belajar', 'Berubat', 'Membeli barang', 'Bersembahyang'], 1),
  q('ms-2-026', 2, 'malay', 'Pilih kata adjektif:', ['Berlari', 'Meja', 'Indah', 'Dengan'], 2),
  q('ms-2-027', 2, 'malay', 'Mereka ___ di taman.', ['am', 'berada', 'is', 'are'], 1),
  q('ms-2-028', 2, 'malay', 'Yang manakah nombor?', ['Biru', 'Lari', 'Tiga', 'Bunga'], 2),
  q('ms-2-029', 2, 'malay', 'Jamak bagi \\\\\\\\', [':', 'Bunga-bunga', 'Bungas', 'Bungakan'], 0),
  q('ms-2-030', 2, 'malay', '\\\\\\\\', [' merujuk kepada?', 'Saya', 'Orang kedua', 'Orang ketiga lebih dari satu'], 2),
  q('ms-2-031', 2, 'malay', 'Lawannya \\\\\\\\', ['?', 'Pendek', 'Berat', 'Kurus'], 1),
  q('ms-2-032', 2, 'malay', 'Hari pertama dalam minggu (BM)?', ['Isnin', 'Ahad', 'Jumaat', 'Sabtu'], 0),
  q('ms-2-033', 2, 'malay', 'Anak kambing dipanggil?', ['Anak sapi', 'Anak kuda', 'Anak kambing', 'Anak harimau'], 2),
  q('ms-2-034', 2, 'malay', 'Kita pergi ke sekolah untuk?', ['Berubat', 'Bermain sahaja', 'Belajar', 'Tidur'], 2),
  q('ms-2-035', 2, 'malay', 'Pilih kata nama:', ['Berlari', 'Cantik', 'Sekolah', 'Cepat'], 2),
  q('ms-2-036', 2, 'malay', 'Dia ___ ke sekolah setiap hari.', ['pergi', 'pergis', 'pergian', 'telah-pergi-pergi'], 0),
  q('ms-2-037', 2, 'malay', 'Yang manakah bulan?', ['Isnin', 'Jumaat', 'Mac', 'Sabtu'], 2),
  q('ms-2-038', 2, 'malay', 'Jamak bagi \\\\\\\\', [':', 'Haiwan-haiwan', 'Haiwans', 'Haiwanik'], 0),
  q('ms-2-039', 2, 'malay', '\\\\\\\\', [' bermaksud?', 'Saya', 'Kamu/engkau', 'Mereka'], 1),
  q('ms-2-040', 2, 'malay', 'Lawannya \\\\\\\\', ['?', 'Besar', 'Lambat/perlahan', 'Kuat'], 1),
  q('ms-2-041', 2, 'malay', 'Hari selepas Ahad?', ['Sabtu', 'Jumaat', 'Isnin', 'Rabu'], 2),
  q('ms-2-042', 2, 'malay', 'Anak harimau dipanggil?', ['Anak singa', 'Anak harimau', 'Anak kuda', 'Anak ikan'], 1),
  q('ms-2-043', 2, 'malay', 'Kita pergi ke masjid untuk?', ['Berubat', 'Belajar', 'Beribadah', 'Membeli barang'], 2),
  q('ms-2-044', 2, 'malay', 'Pilih kata kerja:', ['Meja', 'Cantik', 'Menulis', 'Sekolah'], 2),
  q('ms-2-045', 2, 'malay', 'Kami ___ di sini sekarang.', ['am', 'is', 'berada', 'are'], 2),
  q('ms-2-046', 2, 'malay', 'Yang manakah hari?', ['Januari', 'Kuning', 'Selasa', 'Musim'], 2),
  q('ms-2-047', 2, 'malay', 'Jamak bagi \\\\\\\\', [':', 'Burung-burung', 'Burungs', 'Burungkan'], 0),
  q('ms-2-048', 2, 'malay', '\\\\\\\\', [' biasanya merujuk kepada?', 'Kanak-kanak', 'Orang yang dihormati', 'Benda'], 1),
  q('ms-2-049', 2, 'malay', 'Lawannya \\\\\\\\', ['?', 'Haus', 'Penat', 'Kenyang'], 2),
  q('ms-2-050', 2, 'malay', 'Berapa bulan yang mempunyai 30 hari?', ['2', '3', '4', '5'], 2),
  q('ms-2-051', 2, 'malay', 'Anak singa dipanggil?', ['Anak harimau', 'Anak singa', 'Anak kuda', 'Anak anjing'], 1),
  q('ms-2-052', 2, 'malay', 'Pilih kata adjektif:', ['Berjalan', 'Bermain', 'Comel', 'Sekolah'], 2),
  q('ms-2-053', 2, 'malay', 'Mereka ___ bermain semalam.', ['akan', 'sedang', 'telah', 'adalah'], 2),
  q('ms-2-054', 2, 'malay', 'Yang manakah musim (di negara empat musim)?', ['Merah', 'Isnin', 'Musim bunga', 'Kucing'], 2),
  q('ms-2-055', 2, 'malay', 'Jamak bagi \\\\\\\\', [':', 'Kereta-kereta', 'Keretas', 'Keretak'], 0),
  q('ms-2-056', 2, 'malay', '\\\\\\\\', [' merujuk kepada?', 'Saya', 'Kamu (formal)', 'Mereka'], 1),
  q('ms-2-057', 2, 'malay', 'Lawannya \\\\\\\\', ['?', 'Suka', 'Cergas', 'Sedih'], 2),
  q('ms-2-058', 2, 'malay', 'Hari selepas Sabtu?', ['Jumaat', 'Isnin', 'Ahad', 'Khamis'], 2),
  q('ms-2-059', 2, 'malay', 'Anak kuda dipanggil?', ['Anak sapi', 'Anak kuda', 'Anak lembu', 'Anak kambing'], 1),
  q('ms-2-060', 2, 'malay', 'Kita pergi ke kedai buku untuk?', ['Berubat', 'Membeli buku', 'Belajar', 'Bersembahyang'], 1),
  q('ms-2-061', 2, 'malay', 'Pilih kata nama:', ['Berlari', 'Indah', 'Pantai', 'Cepat'], 2),
  q('ms-2-062', 2, 'malay', 'Dia ___ makan nasi tadi.', ['akan', 'sedang sekarang', 'telah', 'adalah'], 2),
  q('ms-2-063', 2, 'malay', 'Yang manakah warna?', ['Berjalan', 'Hijau', 'Sekolah', 'Meja'], 1),
  q('ms-2-064', 2, 'malay', 'Jamak bagi \\\\\\\\', [':', 'Bintang-bintang', 'Bintangs', 'Bintangis'], 0),
  q('ms-2-065', 2, 'malay', '\\\\\\\\', [' biasanya merujuk kepada?', 'Orang pertama', 'Orang kedua', 'Benda atau haiwan'], 2),
  q('ms-2-066', 2, 'malay', 'Lawannya \\\\\\\\', ['?', 'Berat', 'Lembut', 'Basah'], 1),
  q('ms-2-067', 2, 'malay', 'Hari selepas Selasa?', ['Isnin', 'Khamis', 'Rabu', 'Jumaat'], 2),
  q('ms-2-068', 2, 'malay', 'Anak itik dipanggil?', ['Anak kambing', 'Anak lembu', 'Anak itik', 'Anak kuda'], 2),
  q('ms-2-069', 2, 'malay', 'Kita pergi ke perpustakaan untuk?', ['Berubat', 'Bersenam', 'Membaca dan meminjam buku', 'Bermain'], 2),
  q('ms-2-070', 2, 'malay', 'Pilih kata kerja:', ['Sekolah', 'Besar', 'Memasak', 'Biru'], 2),
  q('ms-2-071', 2, 'malay', 'Kami ___ bermain di taman esok.', ['telah', 'sedang', 'akan', 'adalah'], 2),
  q('ms-2-072', 2, 'malay', 'Yang manakah buah-buahan?', ['Lobak', 'Timun (sayur)', 'Mangga', 'Bayam'], 2),
  q('ms-2-073', 2, 'malay', 'Jamak bagi \\\\\\\\', [':', 'Anak-anak', 'Anaks', 'Anakis'], 0),
  q('ms-2-074', 2, 'malay', 'Lawannya \\\\\\\\', ['?', 'Lemah', 'Rendah', 'Muda'], 2),
  q('ms-2-075', 2, 'malay', 'Bulan pertama dalam tahun?', ['Mac', 'Februari', 'Januari', 'April'], 2),
  q('ms-2-076', 2, 'malay', 'Anak arnab dipanggil?', ['Anak kambing', 'Anak arnab', 'Anak kuda', 'Anak harimau'], 1),
  q('ms-2-077', 2, 'malay', 'Pilih kata adjektif:', ['Berlari', 'Menulis', 'Pandai', 'Sekolah'], 2),
  q('ms-2-078', 2, 'malay', 'Dia ___ belajar sekarang.', ['telah', 'akan', 'sedang', 'adalah'], 2),
  q('ms-2-079', 2, 'malay', 'Yang manakah sayur-sayuran?', ['Pisang', 'Mangga', 'Bayam', 'Limau'], 2),
  q('ms-2-080', 2, 'malay', 'Jamak bagi \\\\\\\\', [':', 'Rumah-rumah', 'Rumahs', 'Rumahen'], 0),
  q('ms-2-081', 2, 'malay', '\\\\\\\\', [' bermaksud?', 'Saya sahaja', 'Kamu sahaja', 'Saya dan kamu (dan mungkin orang lain)'], 2),
  q('ms-2-082', 2, 'malay', 'Lawannya \\\\\\\\', ['?', 'Takut', 'Marah', 'Sayang/suka'], 2),
  q('ms-2-083', 2, 'malay', 'Bulan terakhir dalam tahun?', ['November', 'Oktober', 'Disember', 'Januari'], 2),
  q('ms-2-084', 2, 'malay', 'Anak kucing dipanggil?', ['Anak kuda', 'Anak lembu', 'Anak kucing', 'Anak anjing'], 2),
  q('ms-2-085', 2, 'malay', 'Pilih kata nama:', ['Berlompat', 'Besar', 'Gunung', 'Cepat'], 2),
  q('ms-2-086', 2, 'malay', 'Mereka ___ pergi ke pasar esok.', ['telah', 'sedang', 'akan', 'adalah'], 2),
  q('ms-2-087', 2, 'malay', 'Yang manakah haiwan?', ['Meja', 'Kerusi', 'Harimau', 'Buku'], 2),
  q('ms-2-088', 2, 'malay', 'Jamak bagi \\\\\\\\', [':', 'Teman-teman', 'Temans', 'Temanen'], 0),
  q('ms-2-089', 2, 'malay', 'Lawannya \\\\\\\\', ['?', 'Membuka', 'Berakhir/tamat', 'Berterusan'], 1),
  q('ms-2-090', 2, 'malay', 'Hari ketiga dalam minggu (BM)?', ['Isnin', 'Selasa', 'Rabu', 'Khamis'], 2),
  q('ms-2-091', 2, 'malay', 'Anak gajah dipanggil?', ['Anak kuda', 'Anak gajah', 'Anak harimau', 'Anak lembu'], 1),
  q('ms-2-092', 2, 'malay', 'Pilih kata kerja:', ['Meja', 'Besar', 'Membaca', 'Sekolah'], 2),
  q('ms-2-093', 2, 'malay', 'Saya ___ di rumah semalam.', ['akan', 'sedang sekarang', 'berada', 'adalah'], 2),
  q('ms-2-094', 2, 'malay', 'Yang manakah hari bekerja biasa?', ['Sabtu', 'Ahad', 'Isnin', 'Cuti umum'], 2),
  q('ms-2-095', 2, 'malay', 'Jamak bagi \\\\\\\\', [':', 'Jalan-jalan', 'Jalans', 'Jalanen'], 0),
  q('ms-2-096', 2, 'malay', 'Lawannya \\\\\\\\', ['?', 'Dalam', 'Jauh', 'Sempit'], 1),
  q('ms-2-097', 2, 'malay', 'Hari keempat dalam minggu (BM)?', ['Rabu', 'Selasa', 'Khamis', 'Jumaat'], 2),
  q('ms-2-098', 2, 'malay', 'Anak katak dipanggil?', ['Berudu/anak katak', 'Anak lembu', 'Anak kuda', 'Anak burung'], 0),
  q('ms-2-099', 2, 'malay', 'Kita pergi ke kedai runcit untuk?', ['Berubat', 'Belajar', 'Membeli keperluan harian', 'Bersembahyang'], 2),
  q('ms-2-100', 2, 'malay', 'Pilih kata adjektif:', ['Berlari', 'Memasak', 'Rajin', 'Sekolah'], 2),

  // ── Grade 3 ──────────────────────────────────────────────────────────────
  q('ms-3-001', 3, 'malay', 'pe- + ajar =', ['Pelajar', 'Pengajar saja', 'Ajaran', 'Belajar'], 0),
  q('ms-3-002', 3, 'malay', 'Mereka ___ gembira.', ['adalah', 'am', 'is', 'be'], 0),
  q('ms-3-003', 3, 'malay', 'Sinonim \\\\\\\\', [':', 'Sedih', 'Suka cita', 'Marah'], 1),
  q('ms-3-004', 3, 'malay', 'Orang yang mengajar dipanggil?', ['Doktor', 'Guru', 'Pemandu', 'Juruterbang'], 1),
  q('ms-3-005', 3, 'malay', 'Buku ___ meja', ['di atas', 'sangat', 'segera', 'oleh'], 0),
  q('ms-3-006', 3, 'malay', 'Antonim \\\\\\\\', [':', 'Laju', 'Perlahan', 'Segera'], 1),
  q('ms-3-007', 3, 'malay', '\\\\\\\\', [' menunjukkan?', 'Keupayaan', 'Warna', 'Tempat'], 0),
  q('ms-3-008', 3, 'malay', 'Bandingan: Ali ___ daripada Abu.', ['lebih tinggi', 'tinggi', 'paling', 'tinggi sekali'], 0),
  q('ms-3-009', 3, 'malay', 'Kata soal:', ['Di mana', 'Buku', 'Hijau', 'Perlahan'], 0),
  q('ms-3-010', 3, 'malay', 'Jamak \\\\\\\\', [':', 'Kaki-kaki', 'Kakies', 'Foots'], 0),
  q('ms-3-011', 3, 'malay', 'me- + tulis =', ['Manulis', 'Menulis', 'Metulis', 'Bertulis'], 1),
  q('ms-3-012', 3, 'malay', 'Sinonim \\\\\\\\', [':', 'Hodoh', 'Jelik', 'Indah'], 2),
  q('ms-3-013', 3, 'malay', 'Orang yang merawat pesakit?', ['Guru', 'Peguam', 'Doktor/jururawat', 'Jurutera'], 2),
  q('ms-3-014', 3, 'malay', 'Kucing ___ meja.', ['di atas', 'sangat', 'dengan cepat', 'oleh'], 0),
  q('ms-3-015', 3, 'malay', 'Antonim \\\\\\\\', [':', 'Cergas', 'Kuat', 'Sakit'], 2),
  q('ms-3-016', 3, 'malay', '\\\\\\\\', [' menunjukkan?', 'Kemestian/kewajipan', 'Warna', 'Tempat'], 0),
  q('ms-3-017', 3, 'malay', 'Darjah bandingan: \\\\\\\\', [' menunjukkan darjah?', 'Darjah biasa', 'Darjah lebih', 'Darjah paling/superlatif'], 2),
  q('ms-3-018', 3, 'malay', 'Kata soal untuk tempat?', ['Siapa', 'Bila', 'Di mana', 'Kenapa'], 2),
  q('ms-3-019', 3, 'malay', 'ber- + jalan =', ['Mejalan', 'Berjalan', 'Berjalan sahaja', 'Jalanber'], 1),
  q('ms-3-020', 3, 'malay', 'Sinonim \\\\\\\\', [':', 'Pengecut', 'Takut', 'Gagah/tabah'], 2),
  q('ms-3-021', 3, 'malay', 'Orang yang memandu kereta?', ['Guru', 'Pemandu', 'Doktor', 'Bomba'], 1),
  q('ms-3-022', 3, 'malay', 'Buku itu ___ meja.', ['atas', 'di atas', 'sangat', 'lebih'], 1),
  q('ms-3-023', 3, 'malay', 'Antonim \\\\\\\\', [':', 'Berkilat', 'Kotor', 'Cerah'], 1),
  q('ms-3-024', 3, 'malay', '\\\\\\\\', [' menunjukkan?', 'Saran', 'Larangan', 'Kewajipan'], 2),
  q('ms-3-025', 3, 'malay', 'Bandingan: Bukit ini lebih ___ daripada bukit itu.', ['tinggi', 'paling tinggi', 'tinggi sekali', 'amat tinggi'], 0),
  q('ms-3-026', 3, 'malay', 'Kata soal untuk masa/waktu?', ['Di mana', 'Siapa', 'Bila/kapan', 'Mengapa'], 2),
  q('ms-3-027', 3, 'malay', 'pe- + main =', ['Memain', 'Bermain', 'Pemain', 'Permainan'], 2),
  q('ms-3-028', 3, 'malay', 'Sinonim \\\\\\\\', [':', 'Malas', 'Lalai', 'Tekun/usaha'], 2),
  q('ms-3-029', 3, 'malay', 'Orang yang memadam api?', ['Doktor', 'Guru', 'Anggota bomba', 'Polis'], 2),
  q('ms-3-030', 3, 'malay', 'Adik ___ di bilik.', ['dalam', 'berada di dalam', 'sangat', 'lebih'], 1),
  q('ms-3-031', 3, 'malay', 'Antonim \\\\\\\\', [':', 'Sukar', 'Rumit', 'Mudah/senang'], 2),
  q('ms-3-032', 3, 'malay', '\\\\\\\\', [' menunjukkan?', 'Saranan', 'Larangan', 'Kewajipan'], 1),
  q('ms-3-033', 3, 'malay', 'Bandingan: Ini yang ___ mahal.', ['lebih', 'amat', 'paling/ter-', 'sangat'], 2),
  q('ms-3-034', 3, 'malay', 'Kata soal untuk alasan?', ['Di mana', 'Siapa', 'Bila', 'Mengapa/kenapa'], 3),
  q('ms-3-035', 3, 'malay', 'me- + baca =', ['Mebaca', 'Berbaca', 'Membaca', 'Bacame'], 2),
  q('ms-3-036', 3, 'malay', 'Sinonim \\\\\\\\', [':', 'Baik', 'Sopan', 'Degil/jahat'], 2),
  q('ms-3-037', 3, 'malay', 'Orang yang menjaga undang-undang?', ['Guru', 'Doktor', 'Polis', 'Pemandu'], 2),
  q('ms-3-038', 3, 'malay', 'Bola itu ___ meja.', ['sangat', 'di bawah', 'amat', 'lebih'], 1),
  q('ms-3-039', 3, 'malay', 'Antonim \\\\\\\\', [':', 'Kuat', 'Sihat', 'Miskin'], 2),
  q('ms-3-040', 3, 'malay', '\\\\\\\\', [' bermaksud?', 'Dilarang', 'Mempunyai kebolehan', 'Wajib'], 1),
  q('ms-3-041', 3, 'malay', 'Bandingan: Ali sepintar ___ Ahmad.', ['lebih', 'daripada', 'dengan', 'di'], 2),
  q('ms-3-042', 3, 'malay', 'Kata soal untuk orang?', ['Di mana', 'Bila', 'Siapa', 'Mengapa'], 2),
  q('ms-3-043', 3, 'malay', 'ber- + main =', ['Memain', 'Bermain', 'Permain', 'Mainber'], 1),
  q('ms-3-044', 3, 'malay', 'Sinonim \\\\\\\\', [':', 'Bodoh', 'Dungu', 'Bijak'], 2),
  q('ms-3-045', 3, 'malay', 'Orang yang terbang kapal terbang?', ['Kapten kapal laut', 'Juruterbang', 'Pemandu teksi', 'Konduktor bas'], 1),
  q('ms-3-046', 3, 'malay', 'Dia ___ di rumah sekarang.', ['akan besok', 'sangat', 'berada', 'amat'], 2),
  q('ms-3-047', 3, 'malay', 'Antonim \\\\\\\\', [':', 'Cerah', 'Jelas', 'Gelap'], 2),
  q('ms-3-048', 3, 'malay', '\\\\\\\\', [' menunjukkan?', 'Larangan keras', 'Saranan/cadangan', 'Kewajipan mutlak'], 1),
  q('ms-3-049', 3, 'malay', 'Bandingan paling: Gunung Kinabalu ialah gunung ___ di Malaysia.', ['lebih tinggi', 'tinggi sekali', 'tertinggi/paling tinggi', 'sangat tinggi'], 2),
  q('ms-3-050', 3, 'malay', 'Kata soal untuk cara?', ['Di mana', 'Siapa', 'Bila', 'Bagaimana'], 3),
  q('ms-3-051', 3, 'malay', 'me- + masak =', ['Memasakkan', 'Memasak', 'Bermasak', 'Masak me'], 1),
  q('ms-3-052', 3, 'malay', 'Sinonim \\\\\\\\', [':', 'Berani', 'Garang', 'Cemas/gentar'], 2),
  q('ms-3-053', 3, 'malay', 'Orang yang membina bangunan?', ['Guru', 'Doktor', 'Arkitek/jurutera binaan', 'Polis'], 2),
  q('ms-3-054', 3, 'malay', 'Buku ___ dua pensel.', ['berada di sebelah', 'di antara', 'di celah-celah', 'di hadapan'], 1),
  q('ms-3-055', 3, 'malay', 'Antonim \\\\\\\\', [':', 'Panjang', 'Luas', 'Sempit'], 2),
  q('ms-3-056', 3, 'malay', '\\\\\\\\', [' menunjukkan?', 'Kebolehan', 'Saranan', 'Larangan'], 2),
  q('ms-3-057', 3, 'malay', 'Bandingan: Beg ini lebih berat ___ beg itu.', ['dengan', 'di', 'daripada', 'untuk'], 2),
  q('ms-3-058', 3, 'malay', 'Kata soal untuk bilangan?', ['Siapa', 'Di mana', 'Bila', 'Berapa'], 3),
  q('ms-3-059', 3, 'malay', 'pe- + kerja =', ['Mekerja', 'Berkerja', 'Pekerja', 'Kerjape'], 2),
  q('ms-3-060', 3, 'malay', 'Sinonim \\\\\\\\', [':', 'Kecil', 'Kerdil', 'Agam/hebat'], 2),
  q('ms-3-061', 3, 'malay', 'Orang yang menjual barang di kedai?', ['Doktor', 'Peniaga/penjual', 'Guru', 'Polis'], 1),
  q('ms-3-062', 3, 'malay', 'Anak kucing ___ di bawah kerusi.', ['sangat', 'berada/duduk', 'lebih', 'paling'], 1),
  q('ms-3-063', 3, 'malay', 'Antonim \\\\\\\\', [':', 'Berat', 'Kasar', 'Lembut'], 2),
  q('ms-3-064', 3, 'malay', '\\\\\\\\', [' menunjukkan?', 'Larangan', 'Kebolehan', 'Keperluan'], 2),
  q('ms-3-065', 3, 'malay', 'Bandingan: Dia paling ___ di kelas ini.', ['pandai sekali', 'lebih pandai', 'pandai', 'sangat amat pandai'], 1),
  q('ms-3-066', 3, 'malay', 'Kata soal untuk sebab?', ['Di mana', 'Siapa', 'Berapa', 'Kenapa/mengapa'], 3),
  q('ms-3-067', 3, 'malay', 'me- + dengar =', ['Bedengar', 'Mendengar', 'Mendengarkan sahaja', 'Dengarme'], 1),
  q('ms-3-068', 3, 'malay', 'Sinonim \\\\\\\\', [':', 'Mudah', 'Senang', 'Sukar'], 2),
  q('ms-3-069', 3, 'malay', 'Orang yang mempertahankan negara?', ['Doktor', 'Guru', 'Tentera/askar', 'Nelayan'], 2),
  q('ms-3-070', 3, 'malay', 'Buku ___ rak.', ['sangat', 'di atas', 'lebih', 'paling'], 1),
  q('ms-3-071', 3, 'malay', 'Antonim \\\\\\\\', [':', 'Rendah', 'Kecil', 'Panjang/tinggi'], 2),
  q('ms-3-072', 3, 'malay', '\\\\\\\\', [' menunjukkan?', 'Pilihan', 'Larangan', 'Kewajipan mutlak'], 2),
  q('ms-3-073', 3, 'malay', 'Bandingan: Gunung itu lebih ___ bukit ini.', ['kecil daripada', 'tinggi daripada', 'pendek', 'luas'], 1),
  q('ms-3-074', 3, 'malay', 'Kata soal untuk benda?', ['Siapa (untuk orang)', 'Apa (untuk benda)', 'Bila', 'Di mana'], 1),
  q('ms-3-075', 3, 'malay', 'ber- + tanya =', ['Menanya', 'Bertanya', 'Pertanya', 'Tanyaber'], 1),
  q('ms-3-076', 3, 'malay', 'Sinonim \\\\\\\\', [':', 'Gembira', 'Ceria', 'Dukacita'], 2),
  q('ms-3-077', 3, 'malay', 'Orang yang menjaga hutan?', ['Doktor', 'Penjaga hutan/ranger', 'Peniaga', 'Juruterbang'], 1),
  q('ms-3-078', 3, 'malay', 'Beg ___ kerusi.', ['sangat', 'di belakang', 'lebih', 'paling'], 1),
  q('ms-3-079', 3, 'malay', 'Antonim \\\\\\\\', [':', 'Muda', 'Segar', 'Lama/usang'], 2),
  q('ms-3-080', 3, 'malay', '\\\\\\\\', [' menunjukkan?', 'Wajib', 'Tidak diperlukan/tidak semestinya', 'Dilarang'], 1),
  q('ms-3-081', 3, 'malay', 'Bandingan: Dia sepandai ___.', ['lebih', 'saya', 'paling', 'sangat'], 1),
  q('ms-3-082', 3, 'malay', 'Kata soal untuk pilihan?', ['Di mana', 'Siapa', 'Berapa', 'Yang mana'], 3),
  q('ms-3-083', 3, 'malay', 'pe- + tulis =', ['Menulis', 'Bertulis', 'Penulis', 'Tulispe'], 2),
  q('ms-3-084', 3, 'malay', 'Sinonim \\\\\\\\', [':', 'Lambat', 'Lembap', 'Pantas/laju'], 2),
  q('ms-3-085', 3, 'malay', 'Orang yang memancing ikan?', ['Doktor', 'Nelayan', 'Guru', 'Polis'], 1),
  q('ms-3-086', 3, 'malay', 'Tayar itu ___ kereta.', ['sangat', 'di bawah', 'lebih', 'paling'], 1),
  q('ms-3-087', 3, 'malay', 'Antonim \\\\\\\\', [':', 'Besar', 'Berat', 'Kurus'], 2),
  q('ms-3-088', 3, 'malay', '\\\\\\\\', [' menunjukkan?', 'Larangan', 'Harapan/harapan sopan', 'Kewajipan'], 1),
  q('ms-3-089', 3, 'malay', 'Bandingan: Bilik ini paling ___ dalam rumah.', ['besar sekali', 'lebih besar', 'besar', 'terbesar'], 3),
  q('ms-3-090', 3, 'malay', 'Kata soal untuk jumlah atau harga?', ['Siapa', 'Di mana', 'Bila', 'Berapa'], 3),
  q('ms-3-091', 3, 'malay', 'me- + lihat =', ['Berlihat', 'Melihat', 'Perlihat', 'Lihatme'], 1),
  q('ms-3-092', 3, 'malay', 'Sinonim \\\\\\\\', [':', 'Kasar', 'Keras', 'Lembut/licin'], 2),
  q('ms-3-093', 3, 'malay', 'Orang yang membaiki kereta?', ['Doktor', 'Guru', 'Mekanik', 'Polis'], 2),
  q('ms-3-094', 3, 'malay', 'Lampu ___ siling.', ['berada di', 'sangat di', 'lebih di', 'pada'], 0),
  q('ms-3-095', 3, 'malay', 'Antonim \\\\\\\\', [':', 'Berat', 'Panjang', 'Nipis'], 2),
  q('ms-3-096', 3, 'malay', '\\\\\\\\', [' menunjukkan?', 'Larangan', 'Kewajipan', 'Keinginan'], 2),
  q('ms-3-097', 3, 'malay', 'Bandingan sama: Dia sama tinggi ___ abangnya.', ['daripada', 'lebih', 'dengan', 'di'], 2),
  q('ms-3-098', 3, 'malay', 'Kata soal untuk cara melakukan sesuatu?', ['Siapa', 'Di mana', 'Berapa', 'Bagaimana'], 3),
  q('ms-3-099', 3, 'malay', 'pe- + laut =', ['Berlaut', 'Melaut', 'Pelaut', 'Lautpe'], 2),
  q('ms-3-100', 3, 'malay', 'Sinonim \\\\\\\\', [':', 'Tenang', 'Gembira', 'Murka/garang'], 2),

  // ── Grade 4 ──────────────────────────────────────────────────────────────
  q('ms-4-001', 4, 'malay', 'Kata kerja transitif biasanya ada?', ['Objek', 'Warna', 'Nombor sahaja', 'Lagu'], 0),
  q('ms-4-002', 4, 'malay', '\\\\\\\\', [' ialah?', 'Kata nama', 'Kata adjektif', 'Kata kerja'], 1),
  q('ms-4-003', 4, 'malay', 'Saya suka teh ___ kopi.', ['dan', 'sangat', 'segera', 'si'], 0),
  q('ms-4-004', 4, 'malay', '\\\\\\\\', [' ialah?', 'Frasa adverba', 'Kata nama', 'Nombor'], 0),
  q('ms-4-005', 4, 'malay', 'Tahap tertinggi:', ['Baik', 'Lebih baik', 'Paling baik', 'Baik-baik'], 2),
  q('ms-4-006', 4, 'malay', 'Awalan me- + baca ≈', ['Membaca', 'Pembaca sahaja', 'Bacaan sahaja', 'Dibaca sahaja'], 0),
  q('ms-4-007', 4, 'malay', 'Beberapa orang murid — ini?', ['Frasa bilangan', 'Kata kerja', 'Kata sendi', 'Nombor rom'], 0),
  q('ms-4-008', 4, 'malay', 'Semalam dia ___ ke pasar.', ['pergi', 'akan pergi', 'sedang pergi', 'pergi-pergi'], 0),
  q('ms-4-009', 4, 'malay', '\\\\\\\\', [' bermaksud?', 'Sedih / tidak senang', 'Sangat gembira', 'Lapar'], 0),
  q('ms-4-010', 4, 'malay', 'Watak utama cerita?', ['Protagonis', 'Penerbit', 'Fon', 'Kulit buku'], 0),
  q('ms-4-011', 4, 'malay', 'Kata kerja tak transitif?', ['Ada objek', 'Tidak ada objek langsung', 'Hanya untuk benda', 'Hanya untuk haiwan'], 1),
  q('ms-4-012', 4, 'malay', '\\\\\\\\', [' ialah?', 'Kata nama', 'Kata adjektif', 'Kata kerja'], 1),
  q('ms-4-013', 4, 'malay', 'Dia berjalan ___ taman itu.', ['di', 'dengan', 'di dalam', 'melalui'], 3),
  q('ms-4-014', 4, 'malay', '\\\\\\\\', [' ialah?', 'Frasa nama', 'Frasa kerja', 'Frasa adjektif'], 1),
  q('ms-4-015', 4, 'malay', 'Tahap lebih: Bukit ini ___ tinggi.', ['paling', 'amat', 'lebih', 'sangat'], 2),
  q('ms-4-016', 4, 'malay', 'Awalan ber- + temu =', ['Metemu', 'Bertemu', 'Pertemu', 'Temuber'], 1),
  q('ms-4-017', 4, 'malay', 'Pasukan bola sepak itu — berapa orang sepasukan?', ['9', '10', '11', '12'], 2),
  q('ms-4-018', 4, 'malay', 'Esok dia ___ ke Kuala Lumpur.', ['pergi', 'telah pergi', 'akan pergi', 'sedang pergi'], 2),
  q('ms-4-019', 4, 'malay', 'Sinonim \\\\\\\\', [':', 'Menghalang', 'Menolong', 'Mencaci'], 1),
  q('ms-4-020', 4, 'malay', 'Penceritaan sudut pandang orang pertama?', ['Menggunakan dia/mereka', 'Menggunakan saya/aku', 'Menggunakan kamu', 'Tanpa ganti nama'], 1),
  q('ms-4-021', 4, 'malay', 'Kata kerja aktif lawan?', ['Kata kerja pasif', 'Kata adjektif', 'Kata nama', 'Kata sendi'], 0),
  q('ms-4-022', 4, 'malay', '\\\\\\\\', [' ialah?', 'Kata nama', 'Kata kerja', 'Kata adjektif'], 2),
  q('ms-4-023', 4, 'malay', 'Dia duduk ___ kerusi itu.', ['dalam', 'di atas', 'di antara', 'melalui'], 1),
  q('ms-4-024', 4, 'malay', '\\\\\\\\', [' ialah?', 'Frasa nama', 'Frasa kerja', 'Frasa adjektif'], 2),
  q('ms-4-025', 4, 'malay', 'Awalan ter- menunjukkan?', ['Perbuatan disengajakan', 'Perbuatan tidak disengajakan/tiba-tiba', 'Perintah', 'Larangan'], 1),
  q('ms-4-026', 4, 'malay', 'Ali ___ periksa dengan penuh semangat.', ['akan', 'sedang', 'telah', 'menghadapi'], 3),
  q('ms-4-027', 4, 'malay', 'Antonim \\\\\\\\', [':', 'Canggih', 'Pesat', 'Mundur'], 2),
  q('ms-4-028', 4, 'malay', 'Sudut pandang orang ketiga mengguna?', ['Saya/aku', 'Dia/mereka', 'Kamu/anda', 'Kita'], 1),
  q('ms-4-029', 4, 'malay', 'Ayat aktif: Ali memukul bola. Bentuk pasif?', ['Bola memukul Ali', 'Bola dipukul oleh Ali', 'Ali dipukul bola', 'Bola Ali pukul'], 1),
  q('ms-4-030', 4, 'malay', '\\\\\\\\', [' ialah?', 'Kata nama', 'Kata kerja', 'Kata adjektif'], 2),
  q('ms-4-031', 4, 'malay', 'Dia berjalan ___ jalan itu.', ['dalam', 'di', 'di sepanjang', 'melalui'], 2),
  q('ms-4-032', 4, 'malay', '\\\\\\\\', [' bermaksud?', 'Tangan berbentuk buah', 'Hadiah/oleh-oleh', 'Buah yang mahal'], 1),
  q('ms-4-033', 4, 'malay', 'Awalan di- menunjukkan?', ['Ayat aktif', 'Ayat pasif', 'Ayat tanya', 'Ayat perintah'], 1),
  q('ms-4-034', 4, 'malay', 'Mereka ___ di taman semalam.', ['akan berada', 'sedang berada', 'telah berada', 'pasti berada'], 2),
  q('ms-4-035', 4, 'malay', 'Sinonim \\\\\\\\', [':', 'Cuai', 'Lalai', 'Berwaspada'], 2),
  q('ms-4-036', 4, 'malay', 'Plot cerita melibatkan?', ['Hanya watak', 'Jalan cerita/urutan peristiwa', 'Hanya latar', 'Hanya tema'], 1),
  q('ms-4-037', 4, 'malay', 'Kata kerja berimbuhan me-...-kan?', ['Tidak ada objek', 'Ada objek (transitif)', 'Hanya untuk orang', 'Hanya untuk benda'], 1),
  q('ms-4-038', 4, 'malay', '\\\\\\\\', [' ialah?', 'Kata nama', 'Kata adjektif bermaksud damai', 'Kata kerja'], 1),
  q('ms-4-039', 4, 'malay', 'Dia berjalan ___ pintu itu.', ['melalui', 'sangat', 'lebih', 'paling'], 0),
  q('ms-4-040', 4, 'malay', '\\\\\\\\', [' bermaksud?', 'Batu berbentuk api', 'Bahan penyalaan/unggas api', 'Api yang panas'], 0),
  q('ms-4-041', 4, 'malay', 'Awalan pe- menghasilkan?', ['Kata kerja', 'Kata nama (pelaku/alat)', 'Kata adjektif', 'Kata sendi'], 1),
  q('ms-4-042', 4, 'malay', 'Kawan saya ___ tiba dari Sabah.', ['akan', 'baru sahaja', 'sedang', 'akan sahaja'], 1),
  q('ms-4-043', 4, 'malay', 'Antonim \\\\\\\\', [':', 'Suram', 'Kelam', 'Terang'], 2),
  q('ms-4-044', 4, 'malay', 'Latar dalam cerita bermaksud?', ['Watak utama', 'Tempat dan masa cerita berlaku', 'Tema cerita', 'Konflik utama'], 1),
  q('ms-4-045', 4, 'malay', '\\\\\\\\', [' + -an =?', 'Pelarian', 'Berlarian', 'Perlari'], 1),
  q('ms-4-046', 4, 'malay', '\\\\\\\\', [' ialah?', 'Kata kerja', 'Kata adjektif bermaksud segar', 'Kata nama'], 1),
  q('ms-4-047', 4, 'malay', 'Dia berjalan ___ kawan-kawannya.', ['dalam', 'bersama-sama', 'sangat', 'paling'], 1),
  q('ms-4-048', 4, 'malay', '\\\\\\\\', [' bermaksud?', 'Buah berbentuk hati', 'Orang yang paling disayangi', 'Makanan manis'], 1),
  q('ms-4-049', 4, 'malay', 'Akhiran -kan menunjukkan?', ['Menjadikan untuk orang lain / benefaktif', 'Hanya penyata', 'Hanya larangan', 'Hanya adjektif'], 0),
  q('ms-4-050', 4, 'malay', 'Hari ini dia ___ belajar.', ['telah', 'sedang', 'akan', 'pasti'], 1),
  q('ms-4-051', 4, 'malay', 'Antonim \\\\\\\\', [':', 'Lesu', 'Lusuh', 'Kuat'], 2),
  q('ms-4-052', 4, 'malay', 'Tema cerita bermaksud?', ['Jalan cerita', 'Watak utama', 'Mesej/idea utama cerita', 'Latar tempat'], 2),
  q('ms-4-053', 4, 'malay', 'Kata kerja berimbuhan me-...-i?', ['Tidak ada objek', 'Ada objek (transitif)', 'Hanya untuk benda', 'Hanya adjektif'], 1),
  q('ms-4-054', 4, 'malay', '\\\\\\\\', [' ialah?', 'Kata nama', 'Kata adjektif bermaksud cergas/lintang-pukang', 'Kata kerja'], 1),
  q('ms-4-055', 4, 'malay', 'Mereka berjalan ___ jambatan itu.', ['dalam', 'di atas', 'melalui', 'sangat'], 2),
  q('ms-4-056', 4, 'malay', '\\\\\\\\', [' bermaksud?', 'Tangan yang panjang', 'Suka mencuri', 'Suka memberi'], 1),
  q('ms-4-057', 4, 'malay', 'Akhiran -an menghasilkan?', ['Kata kerja', 'Kata nama (hasil/alat)', 'Kata adjektif', 'Kata sendi'], 1),
  q('ms-4-058', 4, 'malay', 'Semalam dia tidak ___ ke sekolah.', ['pergi', 'akan pergi', 'sedang pergi', 'ingin pergi sekarang'], 0),
  q('ms-4-059', 4, 'malay', 'Sinonim \\\\\\\\', [':', 'Rela', 'Mahu', 'Dipaksa/wajib'], 2),
  q('ms-4-060', 4, 'malay', 'Konflik dalam cerita ialah?', ['Watak yang baik sahaja', 'Masalah atau pertentangan yang mendorong cerita', 'Hanya latar', 'Hanya tema'], 1),
  q('ms-4-061', 4, 'malay', 'Kata kerja berimbuhan memper-?', ['Hanya tak transitif', 'Transitif (ada objek)', 'Hanya adjektif', 'Hanya benda'], 1),
  q('ms-4-062', 4, 'malay', '\\\\\\\\', [' ialah?', 'Kata kerja', 'Kata adjektif bermaksud murah hati', 'Kata nama'], 1),
  q('ms-4-063', 4, 'malay', 'Dia berjalan ___ padang besar itu.', ['melalui/merentas', 'sangat', 'lebih', 'paling'], 0),
  q('ms-4-064', 4, 'malay', '\\\\\\\\', [' bermaksud?', 'Kepala yang keras', 'Degil/tidak mahu ikut nasihat', 'Sangat kuat'], 1),
  q('ms-4-065', 4, 'malay', 'Awalan ber- + pakaian =', ['Mepakaian', 'Berpakaian', 'Perpakaian', 'Pakaiber'], 1),
  q('ms-4-066', 4, 'malay', 'Kelmarin mereka ___ bertemu di sini.', ['akan', 'sedang', 'telah', 'mahu masa depan'], 2),
  q('ms-4-067', 4, 'malay', 'Antonim \\\\\\\\', [':', 'Pembazir', 'Bazir', 'Berjimat-cermat'], 2),
  q('ms-4-068', 4, 'malay', 'Peleraian dalam plot cerita berlaku?', ['Di awal cerita', 'Di pertengahan', 'Selepas konflik diselesaikan', 'Sebelum konflik'], 2),
  q('ms-4-069', 4, 'malay', 'Kata kerja berimbuhan diper-...-kan?', ['Hanya aktif', 'Pasif (benda diperbuatkan)', 'Hanya adjektif', 'Hanya nama'], 1),
  q('ms-4-070', 4, 'malay', '\\\\\\\\', [' ialah?', 'Kata kerja', 'Kata adjektif bermaksud bijak/berjimat', 'Kata nama'], 1),
  q('ms-4-071', 4, 'malay', 'Mereka berjalan ___ kaki lima.', ['merentasi', 'di atas', 'sangat', 'paling'], 1),
  q('ms-4-072', 4, 'malay', '\\\\\\\\', [' bermaksud?', 'Anggota badan', 'Pekerja/pembantu', 'Kaki dan tangan'], 1),
  q('ms-4-073', 4, 'malay', 'Awalan pe- + masak =', ['Memasak', 'Bermasak', 'Pemasakkan', 'Pemasar'], 0),
  q('ms-4-074', 4, 'malay', 'Hari ini dia ___ sedang belajar.', ['telah lepas', 'sedang', 'akan esok', 'akan'], 1),
  q('ms-4-075', 4, 'malay', 'Sinonim \\\\\\\\', [':', 'Bodoh', 'Dungu', 'Arif/bijak'], 2),
  q('ms-4-076', 4, 'malay', 'Klimaks dalam plot berlaku?', ['Di awal', 'Sebelum konflik', 'Di bahagian paling tegang/puncak', 'Selepas peleraian'], 2),
  q('ms-4-077', 4, 'malay', 'Kata kerja berimbuhan memperkan?', ['Hanya pasif', 'Transitif kausatif', 'Hanya adjektif', 'Hanya nama'], 1),
  q('ms-4-078', 4, 'malay', '\\\\\\\\', [' ialah?', 'Kata kerja', 'Kata adjektif bermaksud tulus/jujur', 'Kata nama'], 1),
  q('ms-4-079', 4, 'malay', 'Dia berjalan ___ sungai itu.', ['sangat', 'di tepi', 'lebih', 'paling'], 1),
  q('ms-4-080', 4, 'malay', '\\\\\\\\', [' bermaksud?', 'Tangan yang ringan', 'Rajin membantu', 'Suka bergaduh'], 1),
  q('ms-4-081', 4, 'malay', 'Awalan ke-...-an menghasilkan?', ['Kata kerja biasa', 'Kata nama abstrak', 'Kata adjektif', 'Kata sendi'], 1),
  q('ms-4-082', 4, 'malay', 'Kelmarin mereka ___ di stadium.', ['akan', 'ingin', 'berada/berkumpul', 'nanti'], 2),
  q('ms-4-083', 4, 'malay', 'Antonim \\\\\\\\', [':', 'Dermawan', 'Baik hati', 'Kedekut/bakhil'], 2),
  q('ms-4-084', 4, 'malay', 'Pembinaan ayat aktif: subjek + kata kerja + ?', ['Hanya adjektif', 'Objek (kata nama)', 'Hanya kata sendi', 'Hanya kata hubung'], 1),
  q('ms-4-085', 4, 'malay', '\\\\\\\\', [' ialah?', 'Kata adjektif', 'Kata kerja bermaksud menjimatkan', 'Kata nama'], 1),
  q('ms-4-086', 4, 'malay', 'Mereka berjalan ___ satu baris.', ['dalam', 'secara berbaris/dalam', 'sangat', 'paling'], 1),
  q('ms-4-087', 4, 'malay', '\\\\\\\\', [' bermaksud?', 'Hati yang besar', 'Bangga/gembira', 'Sedih sekali'], 1),
  q('ms-4-088', 4, 'malay', 'Awalan per- + baik =', ['Merbaik', 'Berbaik', 'Perbaik/memperbaik', 'Baikper'], 2),
  q('ms-4-089', 4, 'malay', 'Esok mereka ___ ke Zoo Negara.', ['telah pergi', 'sedang pergi', 'akan pergi', 'baru pergi'], 2),
  q('ms-4-090', 4, 'malay', 'Sinonim \\\\\\\\', [':', 'Kasar', 'Kurang ajar', 'Berbudi bahasa'], 2),
  q('ms-4-091', 4, 'malay', 'Penceritaan orang ketiga terbatas?', ['Tahu semua isi hati semua watak', 'Hanya tahu isi hati satu watak', 'Hanya ada dialog', 'Tanpa latar'], 1),
  q('ms-4-092', 4, 'malay', '\\\\\\\\', [' ialah?', 'Kata nama', 'Kata kerja', 'Kata adjektif bermaksud sabar/teguh'], 2),
  q('ms-4-093', 4, 'malay', 'Dia berlari ___ padang.', ['merentas/merentasi', 'sangat', 'lebih', 'paling'], 0),
  q('ms-4-094', 4, 'malay', '\\\\\\\\', [' bermaksud?', 'Hati yang patah', 'Kecewa/hancur rasa sayang', 'Sangat gembira'], 1),
  q('ms-4-095', 4, 'malay', 'Awalan ke- + tiga =', ['Mertiga', 'Bertiga', 'Ketiga', 'Tigake'], 2),
  q('ms-4-096', 4, 'malay', 'Mereka ___ bermain bola di sana petang tadi.', ['akan', 'ingin', 'telah/sedang', 'nanti'], 2),
  q('ms-4-097', 4, 'malay', 'Antonim \\\\\\\\', [':', 'Tekun', 'Cergas', 'Malas'], 2),
  q('ms-4-098', 4, 'malay', 'Amanat/pengajaran cerita bermaksud?', ['Jalan cerita', 'Latar tempat', 'Nilai atau mesej yang disampaikan', 'Watak utama'], 2),
  q('ms-4-099', 4, 'malay', '\\\\\\\\', [' ialah?', 'Kata kerja', 'Kata nama', 'Kata adjektif bermaksud teguh/pasti'], 2),
  q('ms-4-100', 4, 'malay', 'Pengajaran cerita biasanya terdapat di?', ['Awal cerita', 'Mana-mana bahagian', 'Akhir cerita atau dapat difahami keseluruhan', 'Di tengah sahaja'], 2),

  // ── Grade 5 ──────────────────────────────────────────────────────────────
  q('ms-5-001', 5, 'malay', 'Ayat pasif contoh:', ['Buku itu dibaca oleh Ali', 'Ali buku', 'Biru meja', 'Lari cepat nombor'], 0),
  q('ms-5-002', 5, 'malay', 'Sinonim \\\\\\\\', [':', 'Tamat', 'Bermula', 'Berhenti'], 1),
  q('ms-5-003', 5, 'malay', '\\\\\\\\', [' menunjukkan?', 'Pertentangan', 'Warna', 'Makanan'], 0),
  q('ms-5-004', 5, 'malay', 'Ejaan betul:', ['Sekolah', 'Skolah', 'Sekolahh', 'Cekolah'], 0),
  q('ms-5-005', 5, 'malay', '\\\\\\\\', [' ialah?', 'Simpulan bahasa', 'Peribahasa perumpamaan', 'Kata adjektif'], 1),
  q('ms-5-006', 5, 'malay', 'Antonim \\\\\\\\', [':', 'Sukar', 'Kerap', 'Sedikit'], 1),
  q('ms-5-007', 5, 'malay', 'Personifikasi menjadikan benda?', ['Seperti manusia', 'Seperti nombor', 'Seperti warna', 'Seperti fon'], 0),
  q('ms-5-008', 5, 'malay', 'Perenggan biasanya ada?', ['Satu idea utama', 'Tiada idea', 'Hanya jenaka', 'Hanya nombor'], 0),
  q('ms-5-009', 5, 'malay', 'makan + -an →', ['Makanan', 'Memakan sahaja', 'Pemakan sahaja', 'Dimakan sahaja'], 0),
  q('ms-5-010', 5, 'malay', 'Ejaan betul:', ['Aktiviti', 'Aktivity', 'Activiti', 'Aktivty'], 0),
  q('ms-5-011', 5, 'malay', 'Ayat pasif dengan \\\\\\\\', ['?', 'Kena digunakan dengan kata perintah', 'Kena + kata kerja (golongan ragam pasif)', 'Kena hanya untuk ayat tanya'], 1),
  q('ms-5-012', 5, 'malay', 'Sinonim \\\\\\\\', [':', 'Tenang', 'Selesa', 'Bimbang/gelisah'], 2),
  q('ms-5-013', 5, 'malay', '\\\\\\\\', [' menunjukkan?', 'Pertentangan', 'Sebab/alasan', 'Tujuan'], 1),
  q('ms-5-014', 5, 'malay', 'Ejaan betul:', ['Perniagaan', 'Perniagaan sahaja', 'Peniagaan', 'Perniagaaan'], 0),
  q('ms-5-015', 5, 'malay', '\\\\\\\\', [' bermaksud?', 'Ada udang di batu', 'Ada niat atau maksud tersembunyi', 'Mencari udang'], 1),
  q('ms-5-016', 5, 'malay', 'Antonim \\\\\\\\', [':', 'Berat', 'Berat sahaja', 'Adil/saksama'], 2),
  q('ms-5-017', 5, 'malay', 'Hiperbola ialah?', ['Kiasan dengan \\\\', '', 'Penggunaan bahasa yang sangat berlebihan', 'Penyataan langsung'], 1),
  q('ms-5-018', 5, 'malay', 'Struktur perenggan yang baik?', ['Ayat topik, ayat sokongan, ayat penyimpul', 'Hanya ayat topik', 'Hanya ayat sokongan', 'Tiada struktur'], 0),
  q('ms-5-019', 5, 'malay', 'jalan + pe- =', ['Berjalan', 'Pejalan', 'Pejalan kaki', 'Jalanpe'], 1),
  q('ms-5-020', 5, 'malay', 'Ejaan betul:', ['Universiti', 'Universty', 'Unversiti', 'Universiti sahaja'], 0),
  q('ms-5-021', 5, 'malay', 'Ayat pasif dengan ganti nama diri pertama?', ['Dia + kata kerja + oleh saya', 'Saya + kata kerja (tanpa \\\\', ')', 'Saya baca buku itu (aktif)'], 3),
  q('ms-5-022', 5, 'malay', 'Sinonim \\\\\\\\', [':', 'Baik hati', 'Penyayang', 'Bengis/ganas'], 2),
  q('ms-5-023', 5, 'malay', '\\\\\\\\', [' menunjukkan?', 'Sebab', 'Pertentangan', 'Tujuan'], 2),
  q('ms-5-024', 5, 'malay', 'Ejaan betul:', ['Kemerdekaan', 'Kemerdekaaan', 'Kemerdekaan sahaja', 'Kmerdekaan'], 0),
  q('ms-5-025', 5, 'malay', '\\\\\\\\', [' bermaksud?', 'Mudah melakukan sesuatu', 'Usaha sia-sia', 'Rajin bekerja'], 1),
  q('ms-5-025', 5, 'malay', 'Peribahasa: berani kerana benar bermaksud?', ['Mudah melakukan sesuatu', 'Berani kerana berpihak kepada kebenaran', 'Rajin bekerja', 'Keras hati'], 1),
  q('ms-5-027', 5, 'malay', 'Simile menggunakan kata perbandingan?', ['seperti/bagai/umpama', 'lebih/paling', 'sangat/amat', 'pula/juga'], 0),
  q('ms-5-026', 5, 'malay', 'Antonim tamak:', ['Serakah', 'Loba', 'Sederhana', 'Haloba'], 2),
  q('ms-5-029', 5, 'malay', 'kerja + pe- =', ['Bekerja', 'Pekerjaan', 'Pekerja', 'Kerja pe'], 2),
  q('ms-5-030', 5, 'malay', 'Ejaan betul:', ['Jawatankuasa', 'Jawatankussa', 'Jawatankusa', 'Jawatankuasaa'], 0),
  q('ms-5-031', 5, 'malay', 'Dalam ayat pasif, pelaku diletakkan?', ['Di hadapan', 'Di tengah', 'Selepas kata kerja pasif, didahului \\\\\\\\', ''], 2),
  q('ms-5-032', 5, 'malay', 'Sinonim \\\\\\\\', [':', 'Bersemangat', 'Cekal', 'Kecewa/hilang harapan'], 2),
  q('ms-5-033', 5, 'malay', '\\\\\\\\', [' menunjukkan?', 'Sebab', 'Tujuan', 'Syarat'], 2),
  q('ms-5-034', 5, 'malay', 'Ejaan betul:', ['Perpustakaan', 'Perpustakaaan', 'Perpustakaan sahaja', 'Perputakaan'], 0),
  q('ms-5-035', 5, 'malay', '\\\\\\\\', [' bermaksud?', 'Saling bergantung dan membantu', 'Berkonflik', 'Tidak saling kenal'], 0),
  q('ms-5-036', 5, 'malay', 'Antonim \\\\\\\\', [':', 'Keras kepala', 'Tetap pendirian', 'Mendengar nasihat/taat'], 2),
  q('ms-5-037', 5, 'malay', 'Metafora tidak menggunakan?', ['seperti/bagai', 'Kata perbandingan terus', 'Perbandingan langsung', 'Kiasan'], 0),
  q('ms-5-038', 5, 'malay', 'Pengenalan karangan berfungsi?', ['Mengakhiri perbincangan', 'Memperkenalkan topik dan menarik minat pembaca', 'Hanya menulis tarikh', 'Hanya menulis nama'], 1),
  q('ms-5-039', 5, 'malay', 'dagang + pe- =', ['Berdagang', 'Pedagang', 'Pedagang', 'Dagangpe'], 1),
  q('ms-5-040', 5, 'malay', 'Ejaan betul:', ['Kebudayaan', 'Kebudayaaan', 'Keboudayaan', 'Kebuadayaan'], 0),
  q('ms-5-041', 5, 'malay', 'Ayat pasif dengan ganti nama diri kedua?', ['Saya + kata kerja', 'Kamu + kata kerja aktif sahaja', 'Kamu/anda + kata kerja pasif diri', 'Dia + oleh kamu'], 2),
  q('ms-5-042', 5, 'malay', 'Sinonim \\\\\\\\', [':', 'Terdedah', 'Berlari', 'Berteduh/berlindung diri'], 2),
  q('ms-5-043', 5, 'malay', '\\\\\\\\', [' menunjukkan?', 'Sebab', 'Tujuan', 'Dua perbuatan berlaku serentak'], 2),
  q('ms-5-044', 5, 'malay', 'Ejaan betul:', ['Kemudahan', 'Kemudhaan', 'Kemudaahan', 'Kemudaahn'], 0),
  q('ms-5-045', 5, 'malay', '\\\\\\\\', [' bermaksud?', 'Kacang tidak ada kulit', 'Lupa asal usul atau jasa orang yang membesarkan', 'Tidak suka kacang'], 1),
  q('ms-5-046', 5, 'malay', 'Antonim \\\\\\\\', [':', 'Angkuh', 'Takbur', 'Rendah diri/merendah diri'], 2),
  q('ms-5-047', 5, 'malay', 'Asonansi ialah?', ['Pengulangan bunyi konsonan', 'Pengulangan bunyi vokal dalam satu baris sajak', 'Kiasan', 'Simile'], 1),
  q('ms-5-048', 5, 'malay', 'Isi karangan berfungsi?', ['Membuka perbincangan', 'Mengembangkan dan menyokong idea utama', 'Menutup karangan', 'Hanya menulis tarikh'], 1),
  q('ms-5-049', 5, 'malay', 'nasihat + ke-...-an =', ['Menasihati', 'Penasihat', 'Kenasihat', 'Penasihat sahaja'], 2),
  q('ms-5-050', 5, 'malay', 'Ejaan betul:', ['Pengetahuan', 'Pengatahaun', 'Pengethauan', 'Pengetahuaan'], 0),
  q('ms-5-051', 5, 'malay', 'Dalam karangan berita, siapa yang menulis?', ['Pengarang fiksyen', 'Wartawan/pemberita', 'Pelajar sahaja', 'Guru sahaja'], 1),
  q('ms-5-052', 5, 'malay', 'Sinonim \\\\\\\\', [':', 'Lemah', 'Tidak pasti', 'Tegas/kuat'], 2),
  q('ms-5-053', 5, 'malay', '\\\\\\\\', [' menunjukkan?', 'Sebab', 'Syarat', 'Waktu'], 2),
  q('ms-5-054', 5, 'malay', 'Ejaan betul:', ['Tanggungjawab', 'Tangungjawab', 'Tanggungjawap', 'Tanggungjawab sahaja'], 0),
  q('ms-5-055', 5, 'malay', '\\\\\\\\', [' bermaksud?', 'Melentur kayu tua', 'Mendidik anak sejak kecil lebih mudah', 'Melentur buluh sahaja'], 1),
  q('ms-5-056', 5, 'malay', 'Antonim \\\\\\\\', [':', 'Gigih', 'Tekun', 'Sambil lewa/tidak serius'], 2),
  q('ms-5-057', 5, 'malay', 'Aliterasi ialah?', ['Pengulangan bunyi vokal', 'Pengulangan bunyi konsonan awal dalam satu baris', 'Kiasan biasa', 'Perbandingan dengan \\\\'], 1),
  q('ms-5-058', 5, 'malay', 'Penutup karangan berfungsi?', ['Memperkenalkan topik', 'Mengembangkan isi', 'Merumus dan menyimpulkan perbincangan', 'Hanya menulis nama'], 2),
  q('ms-5-059', 5, 'malay', 'tulis + pe- =', ['Menulis', 'Bertulis', 'Penulis', 'Tulispe'], 2),
  q('ms-5-060', 5, 'malay', 'Ejaan betul:', ['Persekitaran', 'Perseketaran', 'Persekitaraan', 'Persekitaran sahaja'], 0),
  q('ms-5-061', 5, 'malay', 'Jenis-jenis karangan termasuk?', ['Hanya karangan cerita', 'Karangan cerita, berita, rencana, surat dll.', 'Hanya karangan berita', 'Hanya surat rasmi'], 1),
  q('ms-5-062', 5, 'malay', 'Sinonim \\\\\\\\', [':', 'Malas', 'Leka', 'Rajin/gigih'], 2),
  q('ms-5-063', 5, 'malay', '\\\\\\', [' dan \\\\', ' menunjukkan?', 'Sebab', 'Tujuan'], 2),
  q('ms-5-064', 5, 'malay', 'Ejaan betul:', ['Pembangunan', 'Pembangun', 'Pembangguan', 'Pembangunaan'], 0),
  q('ms-5-065', 5, 'malay', '\\\\', [' bermaksud?', 'Saling tolong menolong', 'Mementingkan diri sendiri', 'Menolong semua orang'], 1),
  q('ms-5-066', 5, 'malay', 'Antonim \\\\', [':', 'Jujur', 'Tulus', 'Munafik/tidak ikhlas'], 2),
  q('ms-5-067', 5, 'malay', 'Repetisi dalam puisi ialah?', ['Kiasan dengan \\', '', 'Pengulangan kata/frasa untuk kesan tertentu', 'Perbandingan langsung'], 1),
  q('ms-5-068', 5, 'malay', 'Surat rasmi berbeza dengan surat tidak rasmi?', ['Surat rasmi lebih peribadi', 'Surat rasmi mempunyai format tetap dan bahasa formal', 'Surat tidak rasmi lebih panjang', 'Tidak ada perbezaan'], 1),
  q('ms-5-069', 5, 'malay', 'sayang + ke-...-an =', ['Menyayangi', 'Penyayang', 'Kesayangan', 'Sayangke'], 2),
  q('ms-5-070', 5, 'malay', 'Ejaan betul:', ['Kepimpinan', 'Kepimpinaan', 'Kepempinan', 'Kepimpinanaa'], 0),
  q('ms-5-071', 5, 'malay', 'Karangan jenis perbahasan memerlukan?', ['Hanya satu pendapat', 'Hujah menyokong dan menentang', 'Hanya fakta', 'Hanya cerita'], 1),
  q('ms-5-072', 5, 'malay', 'Sinonim \\\\\\\\', [':', 'Berjaya', 'Menang', 'Kalah/tidak berjaya'], 2),
  q('ms-5-073', 5, 'malay', '\\\\\\\\', [' digunakan untuk?', 'Menunjukkan pertentangan', 'Menambah maklumat', 'Menunjukkan sebab'], 1),
  q('ms-5-074', 5, 'malay', 'Ejaan betul:', ['Kesetiaan', 'Kesetian', 'Kesatian', 'Kesetiaan sahaja'], 0),
  q('ms-5-075', 5, 'malay', '\\\\\\\\', [' — unsur bahasa ini ialah?', 'Hiperbola', 'Simile (perbandingan dengan \\\\', ')'], 1),
  q('ms-5-076', 5, 'malay', 'Antonim \\\\\\\\', [':', 'Amanah', 'Benar', 'Berbohong/tidak jujur'], 2),
  q('ms-5-077', 5, 'malay', 'Sinkof ialah?', ['Penambahan bunyi di awal kata', 'Pengguguran bunyi di tengah kata', 'Pengguguran bunyi di akhir kata', 'Pengguguran bunyi di awal'], 1),
  q('ms-5-078', 5, 'malay', 'Penggunaan kata hubung \\\\\\\\', [' dalam karangan?', 'Menunjukkan sebab sahaja', 'Menunjukkan kesimpulan atau akibat', 'Menunjukkan tujuan'], 1),
  q('ms-5-079', 5, 'malay', 'dengar + pe- =', ['Mendengar', 'Berdengar', 'Pendengar', 'Dengape'], 2),
  q('ms-5-080', 5, 'malay', 'Ejaan betul:', ['Warganegara', 'Warganegaraa', 'Wargane gara', 'Warga negara (boleh dipisahkan)'], 0),
  q('ms-5-081', 5, 'malay', 'Karangan surat kepada editor memerlukan?', ['Format surat peribadi', 'Format surat rasmi dan hujah berkesan', 'Format nota', 'Format berita sahaja'], 1),
  q('ms-5-082', 5, 'malay', 'Sinonim \\\\\\\\', [':', 'Boros', 'Pembazir', 'Berjimat-cermat'], 2),
  q('ms-5-083', 5, 'malay', '\\\\\\\\', [' digunakan untuk?', 'Menunjukkan perbezaan ringan', 'Menambah penekanan atau lebih-lebih lagi', 'Menunjukkan syarat'], 1),
  q('ms-5-084', 5, 'malay', 'Ejaan betul:', ['Keharmonian', 'Keharmoniaan', 'Keharminoan', 'Keharmunian'], 0),
  q('ms-5-085', 5, 'malay', '\\\\\\\\', [' menggunakan awalan?', 'me-', 'pe-', 'ber-'], 2),
  q('ms-5-086', 5, 'malay', 'Antonim \\\\\\\\', [':', 'Mesra', 'Lunak', 'Pendiam/pemalu'], 2),
  q('ms-5-087', 5, 'malay', 'Apostrof dalam ejaan Rumi digunakan untuk?', ['Menunjukkan pemilikan', 'Menunjukkan singkatan atau hentian glotis', 'Menunjukkan nama khas', 'Tiada fungsi'], 1),
  q('ms-5-088', 5, 'malay', 'Dalam karangan rencana, penulis menggunakan?', ['Bahasa tidak formal dan emosi sahaja', 'Bahasa formal dengan fakta dan hujah', 'Hanya dialog', 'Hanya puisi'], 1),
  q('ms-5-089', 5, 'malay', 'baca + pe- =', ['Membaca', 'Berbaca', 'Pembaca', 'Bacape'], 2),
  q('ms-5-090', 5, 'malay', 'Ejaan betul:', ['Tanggungjawab', 'Tanggongjawab', 'Tanggungjawap', 'Tanggungjawabs'], 0),
  q('ms-5-091', 5, 'malay', 'Karangan dialog (perbualan) mestilah?', ['Tiada tanda baca', 'Ada nama penutur dan tanda petik', 'Hanya bahasa baku', 'Hanya bahasa pasar'], 1),
  q('ms-5-092', 5, 'malay', 'Sinonim \\\\\\\\', [':', 'Lesu', 'Layu', 'Berapi-api/ghairah'], 2),
  q('ms-5-093', 5, 'malay', '\\\\\\\\', [' digunakan untuk?', 'Menunjukkan syarat', 'Menambah penekanan/lebih daripada yang dijangka', 'Menunjukkan tujuan'], 1),
  q('ms-5-094', 5, 'malay', 'Ejaan betul:', ['Masyarakat', 'Masarakat', 'Masyarakaat', 'Mayarakat'], 0),
  q('ms-5-095', 5, 'malay', '\\\\\\\\', [' bermaksud?', 'Hampir sama', 'Sangat jauh bezanya', 'Agak berbeza'], 1),
  q('ms-5-096', 5, 'malay', 'Antonim \\\\\\\\', [':', 'Kecewa', 'Lemah semangat', 'Tabah/cekal/tidak berputus asa'], 2),
  q('ms-5-097', 5, 'malay', 'Eufemisme ialah?', ['Kata kasar', 'Kata yang lebih halus bagi sesuatu yang sensitif', 'Hiperbola', 'Metafora'], 1),
  q('ms-5-098', 5, 'malay', 'Penutup karangan yang baik?', ['Memperkenalkan idea baru', 'Merumus isi dan memberikan penutup yang berkesan', 'Hanya menulis nama', 'Hanya menulis tarikh'], 1),
  q('ms-5-099', 5, 'malay', 'sabar + ke-...-an =', ['Menyabar', 'Penyabar', 'Kesabaran', 'Sabaran'], 2),
  q('ms-5-100', 5, 'malay', 'Ejaan betul:', ['Mengecualikan', 'Mengkecualikan', 'Mengecualian', 'Mengecualikaan'], 0),

  // ── Grade 6 ──────────────────────────────────────────────────────────────
  q('ms-6-001', 6, 'malay', 'Ayat majmuk diganding dengan?', ['Kata hubung', 'Hanya warna', 'Hanya nombor', 'Hanya fon'], 0),
  q('ms-6-002', 6, 'malay', '\\\\\\\\', [' ialah?', 'Perbandingan / kiasan', 'Nombor', 'Arahan'], 0),
  q('ms-6-003', 6, 'malay', 'Salam formal surat:', ['Hai bro', 'Tuan/Puan', 'Yo', 'Sup'], 1),
  q('ms-6-004', 6, 'malay', 'Teks persuasif bertujuan?', ['Memujuk', 'Menidurkan', 'Menyanyi', 'Mengira sahaja'], 0),
  q('ms-6-005', 6, 'malay', '\\\\\\\\', [' bermaksud?', 'Rajin', 'Malas', 'Sakit'], 0),
  q('ms-6-006', 6, 'malay', 'Murid ___ menang ialah adik saya.', ['yang', 'di mana', 'apabila', 'berapa'], 0),
  q('ms-6-007', 6, 'malay', 'Tema karya bermaksud?', ['Mesej utama', 'Bilangan muka surat', 'Harga kulit', 'Umur penulis'], 0),
  q('ms-6-008', 6, 'malay', 'Ejaan betul:', ['Falsafah', 'Filsafat', 'Falsafahh', 'Falsapah'], 0),
  q('ms-6-009', 6, 'malay', 'Bibliografi ialah senarai?', ['Sumber rujukan', 'Skor sukan', 'Warna', 'Kata laluan'], 0),
  q('ms-6-010', 6, 'malay', 'Kritik sastera menilai?', ['Karya secara berasas', 'Hanya cover', 'Hanya harga', 'Hanya fon'], 0),
  q('ms-6-011', 6, 'malay', 'Ayat majmuk pancangan?', ['Dua ayat setara', 'Satu ayat induk + satu/lebih ayat kecil', 'Hanya satu ayat', 'Tiga ayat bebas'], 1),
  q('ms-6-012', 6, 'malay', '\\\\\\', [' — \\\\', ' ialah?', 'Ayat induk', 'Klausa relatif/ayat kecil relatif'], 1),
  q('ms-6-013', 6, 'malay', 'Penutup surat rasmi?', ['Yang ikhlas', 'Yang benar', 'Kedua-duanya boleh digunakan', 'Tidak perlu penutup'], 2),
  q('ms-6-014', 6, 'malay', 'Nilai murni dalam karya bermaksud?', ['Harga buku', 'Nilai positif yang ingin disampaikan', 'Bilangan watak', 'Nama pengarang'], 1),
  q('ms-6-015', 6, 'malay', '\\\\', [' menggunakan kata perbandingan?', 'lebih', 'paling', 'bagai/seperti'], 2),
  q('ms-6-016', 6, 'malay', 'Kata relatif \\\\', [' digunakan untuk?', 'Menghubungkan ayat setara', 'Menerangkan kata nama (klausa relatif)', 'Menunjukkan masa'], 1),
  q('ms-6-017', 6, 'malay', 'Dalam surat rasmi, format bahagian alamat penerima?', ['Di bahagian kanan bawah', 'Di bahagian kiri atas', 'Di tengah-tengah', 'Di bahagian kanan atas'], 1),
  q('ms-6-018', 6, 'malay', 'Budaya dalam karya sastera merujuk kepada?', ['Hanya makanan', 'Adat resam dan cara hidup masyarakat', 'Hanya pakaian', 'Hanya bahasa'], 1),
  q('ms-6-019', 6, 'malay', '\\\\', [' terbentuk daripada?', 'sayang + pe-...-an', 'sayang + pe-', 'pe- + sayang'], 2),
  q('ms-6-020', 6, 'malay', 'Ejaan betul:', ['Kemajmukan', 'Kemajmukaan', 'Kemajmukanaan', 'Kemajmukan (betul)'], 0),
  q('ms-6-021', 6, 'malay', 'Ayat majmuk gabungan menggunakan?', ['Kata hubung pancangan', 'Kata hubung setara (dan, tetapi, atau)', 'Kata relatif', 'Tiada kata hubung'], 1),
  q('ms-6-022', 6, 'malay', '\\', [' — \\\\', ' ialah?', 'Kata kerja', 'Frasa adjektif relatif (klausa relatif)'], 1),
  q('ms-6-023', 6, 'malay', 'Dalam surat rasmi, tarikh ditulis?', ['Di bawah tandatangan', 'Di sebelah kanan atau kiri atas (selepas alamat penghantar)', 'Di tengah-tengah', 'Di bahagian belakang'], 1),
  q('ms-6-024', 6, 'malay', 'Mesej sosial dalam karya sastera merujuk kepada?', ['Harga buku', 'Pengajaran tentang isu masyarakat yang disampaikan', 'Bilangan muka surat', 'Nama watak'], 1),
  q('ms-6-025', 6, 'malay', '\\\\', [' terbentuk daripada?', 'pimpin + me-', 'pimpin + ber-', 'pe- + pimpin + -an'], 2),
  q('ms-6-026', 6, 'malay', 'Ejaan betul:', ['Kelestarian', 'Kelestariaan', 'Kelistarian', 'Kelestariannya sahaja'], 0),
  q('ms-6-027', 6, 'malay', 'Ayat majmuk relatif menggunakan kata?', ['dan/atau/tetapi', 'yang', 'apabila/kerana', 'oleh itu'], 1),
  q('ms-6-028', 6, 'malay', '\\', [' — \\\\', ' berfungsi sebagai?', 'Ayat induk', 'Frasa adjektif (menerangkan buku)'], 1),
  q('ms-6-029', 6, 'malay', 'Dalam surat tidak rasmi, nada penulisan?', ['Sangat formal dan kaku', 'Mesra dan tidak terikat format ketat', 'Tiada ucapan', 'Hanya fakta'], 1),
  q('ms-6-030', 6, 'malay', 'Watak protagonis ialah?', ['Watak jahat utama', 'Watak baik/utama cerita', 'Watak sampingan', 'Pencerita'], 1),
  q('ms-6-031', 6, 'malay', 'Ayat majmuk dengan \\\\', [' menunjukkan?', 'Gabungan setara', 'Hubungan sebab-akibat', 'Hubungan syarat'], 1),
  q('ms-6-032', 6, 'malay', '\\\\', [' — kata relatif?', 'dan', 'tetapi', 'yang'], 2),
  q('ms-6-033', 6, 'malay', 'Dalam surat rasmi, bahasa yang digunakan?', ['Bahasa pasar', 'Bahasa formal dan baku', 'Bahasa slanga', 'Bahasa puisi'], 1),
  q('ms-6-034', 6, 'malay', 'Antagonis dalam cerita ialah?', ['Watak baik utama', 'Watak yang menentang protagonis', 'Pencerita', 'Pembaca'], 1),
  q('ms-6-035', 6, 'malay', '\\\\', [' terbentuk daripada?', 'urus + pe-', 'pe- + urus + -an', 'urus + me-'], 1),
  q('ms-6-036', 6, 'malay', 'Ejaan betul:', ['Perpaduan', 'Perpanduan', 'Perpaduaan', 'Perpadoan'], 0),
  q('ms-6-037', 6, 'malay', 'Ayat majmuk dengan \\\\', [' menunjukkan?', 'Sebab', 'Tujuan', 'Syarat'], 1),
  q('ms-6-038', 6, 'malay', '\\\\', [' — klausa relatif?', 'budak adik saya', 'yang menangis itu', 'adik saya'], 1),
  q('ms-6-039', 6, 'malay', 'Dalam karangan ilmiah, bahasa yang digunakan?', ['Bahasa santai dan slanga', 'Bahasa formal dan tepat', 'Bahasa puisi', 'Bahasa pasar'], 1),
  q('ms-6-040', 6, 'malay', 'Plot cerita yang berstruktur mengandungi?', ['Hanya klimaks', 'Permulaan, perkembangan, klimaks, peleraian', 'Hanya peleraian', 'Hanya permulaan'], 1),
  q('ms-6-041', 6, 'malay', 'Ayat majmuk dengan \\\\', [' menunjukkan?', 'Sebab', 'Tujuan', 'Syarat'], 2),
  q('ms-6-042', 6, 'malay', '\\\\', [' — klausa relatif?', 'orang dihormati ramai', 'yang berjasa itu', 'dihormati ramai'], 1),
  q('ms-6-043', 6, 'malay', 'Dalam ucapan awam, nada yang sesuai?', ['Sangat formal dan kaku', 'Percakapan biasa sahaja', 'Bertenaga, jelas, dan sesuai audiens', 'Sangat perlahan dan membosankan'], 2),
  q('ms-6-044', 6, 'malay', 'Latar sosial dalam karya merujuk kepada?', ['Tempat fizikal sahaja', 'Masa sahaja', 'Suasana kemasyarakatan dalam cerita', 'Nama watak'], 2),
  q('ms-6-045', 6, 'malay', '\\\\', [' terbentuk daripada?', 'selidik + pe-', 'pe- + selidik + -an', 'selidik + me-'], 1),
  q('ms-6-046', 6, 'malay', 'Ejaan betul:', ['Kemasyarakatan', 'Kemasayarakatan', 'Kemasyarakataan', 'Kemasyarakatan (betul)'], 0),
  q('ms-6-047', 6, 'malay', 'Ayat majmuk keterangan waktu menggunakan?', ['dan/atau', 'apabila/ketika/semasa', 'yang', 'agar/supaya'], 1),
  q('ms-6-048', 6, 'malay', '\\\\', [' — yang tinggi itu ialah?', 'Frasa nama', 'Frasa adjektif (klausa relatif)', 'Frasa kerja'], 1),
  q('ms-6-049', 6, 'malay', 'Dalam esei akademik, kutipan perlu?', ['Tidak perlu sumber', 'Ada sumber/rujukan', 'Diubah sesuka hati', 'Diulang sahaja'], 1),
  q('ms-6-050', 6, 'malay', 'Nilai keberanian dalam karya bermaksud?', ['Takut kepada semua', 'Berani menghadapi cabaran', 'Lari dari masalah', 'Tidak peduli'], 1),
  q('ms-6-051', 6, 'malay', 'Ayat majmuk dengan \\\\', ['?', 'Hubungan sebab', 'Hubungan tujuan', 'Hubungan pertentangan/konsesi'], 2),
  q('ms-6-052', 6, 'malay', '\\\\', [' — klausa relatif?', 'guru disenangi murid', 'yang sabar itu', 'disenangi murid'], 1),
  q('ms-6-053', 6, 'malay', 'Dalam karangan laporan, nada penulisan?', ['Emosional dan peribadi', 'Objektif dan formal', 'Fiksyen dan kreatif', 'Hanya dialog'], 1),
  q('ms-6-054', 6, 'malay', 'Nilai kesetiaan dalam karya bermaksud?', ['Bertukar kumpulan sesuka hati', 'Taat setia kepada negara, agama, atau seseorang yang layak', 'Tidak peduli', 'Hanya kepada wang'], 1),
  q('ms-6-055', 6, 'malay', '\\\\', [' terbentuk daripada?', 'sekitar + pe-...-an', 'sekitar + ber-', 'pe- + sekitar'], 0),
  q('ms-6-056', 6, 'malay', 'Ejaan betul:', ['Kepelbagaian', 'Kepelbagaain', 'Kepelbagaiaan', 'Kepelbagaian (betul)'], 0),
  q('ms-6-057', 6, 'malay', 'Ayat majmuk dengan \\\\', ['?', 'Hubungan tujuan', 'Hubungan sebab', 'Hubungan syarat'], 1),
  q('ms-6-058', 6, 'malay', '\\\\', [' — klausa relatif?', 'yang rendang itu', 'memberikan teduhan', 'pokok'], 0),
  q('ms-6-059', 6, 'malay', 'Dalam penulisan kreatif, diksi merujuk kepada?', ['Bilangan perkataan', 'Pemilihan kata yang tepat dan berkesan', 'Panjang ayat', 'Bilangan perenggan'], 1),
  q('ms-6-060', 6, 'malay', 'Nilai patriotisme bermaksud?', ['Benci negara sendiri', 'Mencintai dan sanggup berkorban untuk negara', 'Hanya suka bendera', 'Hanya suka lagu kebangsaan'], 1),
  q('ms-6-061', 6, 'malay', 'Ayat majmuk dengan \\\\', ['?', 'Hubungan sebab', 'Hubungan pertentangan', 'Hubungan tujuan'], 2),
  q('ms-6-062', 6, 'malay', '\\\\', [' — klausa relatif?', 'seorang melaporkan', 'yang tidak dikenali', 'melaporkan kejadian itu'], 1),
  q('ms-6-063', 6, 'malay', 'Dalam penulisan kreatif, sudut pandang mempengaruhi?', ['Hanya panjang karangan', 'Perspektif dan cara pembaca memahami cerita', 'Hanya bahasa', 'Hanya dialog'], 1),
  q('ms-6-064', 6, 'malay', 'Nilai kasih sayang dalam karya bermaksud?', ['Benci sesama manusia', 'Menyayangi keluarga, rakan, dan sesama insan', 'Hanya sayang harta', 'Hanya sayang haiwan'], 1),
  q('ms-6-065', 6, 'malay', '\\\\', [' terbentuk daripada?', 'bijak + ke-...-an', 'ke- + bijak + -an', 'bijaksana + ke-...-an'], 3),
  q('ms-6-066', 6, 'malay', 'Ejaan betul:', ['Pengkhianatan', 'Penghianatan', 'Pengkhiatan', 'Pengkhianatan (betul)'], 0),
  q('ms-6-067', 6, 'malay', 'Ayat majmuk dengan \\\\', ['?', 'Hubungan tujuan', 'Hubungan sebab', 'Hubungan syarat'], 2),
  q('ms-6-068', 6, 'malay', '\\\\', [' — klausa relatif?', 'yang besar itu', 'diterima dengan gembira', 'hadiah diterima'], 0),
  q('ms-6-069', 6, 'malay', 'Dalam perbahasan, pembahasa perlu?', ['Hanya bercakap kuat', 'Memberikan hujah berkesan dan bersandar fakta', 'Hanya menuduh', 'Hanya mengulang'], 1),
  q('ms-6-070', 6, 'malay', 'Nilai hormat-menghormati bermaksud?', ['Hanya hormat orang tua', 'Saling menghormati antara semua lapisan masyarakat', 'Hanya hormat guru', 'Hanya hormat pemimpin'], 1),
  q('ms-6-071', 6, 'malay', 'Kata hubung \\\\', [' menunjukkan?', 'Sebab', 'Tujuan', 'Syarat'], 3),
  q('ms-6-072', 6, 'malay', '\\\\', [' — klausa relatif?', 'yang cekap itu', 'diserahkan projek besar', 'pegawai projek'], 0),
  q('ms-6-073', 6, 'malay', 'Dalam syarahan, penyampai perlu?', ['Hanya membaca', 'Menyampaikan dengan yakin, jelas, dan berkesan', 'Berbisik sahaja', 'Menghafal sahaja'], 1),
  q('ms-6-074', 6, 'malay', 'Nilai amanah bermaksud?', ['Suka mengkhianati', 'Menjalankan tanggungjawab dengan jujur', 'Hanya mendengar perintah', 'Tidak peduli'], 1),
  q('ms-6-075', 6, 'malay', '\\\\', [' terbentuk daripada?', 'bangun + pe-', 'pe- + bangun + -an', 'bangun + me-...-an'], 1),
  q('ms-6-076', 6, 'malay', 'Ejaan betul:', ['Keterbukaan', 'Keterbukaaan', 'Keterbukakan', 'Keterbukaan (betul)'], 0),
  q('ms-6-077', 6, 'malay', 'Ayat majmuk dengan \\\\', ['?', 'Sebab', 'Tujuan', 'Pertentangan/konsesi'], 2),
  q('ms-6-078', 6, 'malay', '\\\\', [' — frasa nama?', 'Kereta yang merah itu', 'Milik bapa saya', 'Kereta bapa'], 0),
  q('ms-6-079', 6, 'malay', 'Dalam forum, peserta perlu?', ['Bercakap sesuka hati', 'Mengikut giliran dan hormat pendapat orang lain', 'Mengejek pendapat lain', 'Diam sahaja'], 1),
  q('ms-6-080', 6, 'malay', 'Nilai keadilan bermaksud?', ['Pilih kasih', 'Memberi hak kepada yang berhak tanpa berat sebelah', 'Hanya untuk pemimpin', 'Hanya untuk orang kaya'], 1),
  q('ms-6-081', 6, 'malay', 'Kata hubung \\\\', [' menunjukkan?', 'Pertentangan', 'Tujuan', 'Waktu (selepas sesuatu berlaku)'], 2),
  q('ms-6-082', 6, 'malay', '\\\\', [' — klausa relatif?', 'Makanan telah habis', 'Yang lazat itu', 'Telah habis'], 1),
  q('ms-6-083', 6, 'malay', 'Dalam penulisan akademik, abstrak berfungsi?', ['Penutup laporan', 'Ringkasan keseluruhan laporan/kajian', 'Senarai rujukan', 'Pengenalan sahaja'], 1),
  q('ms-6-084', 6, 'malay', 'Nilai tolong-menolong bermaksud?', ['Hanya menolong saudara', 'Saling bantu membantu tanpa mengira latar belakang', 'Hanya untuk mendapat ganjaran', 'Menolong sesekali sahaja'], 1),
  q('ms-6-085', 6, 'malay', '\\\\', [' terbentuk daripada?', 'sedar + ke-...-an', 'ke- + sedar + -an', 'Kedua-duanya sama'], 2),
  q('ms-6-086', 6, 'malay', 'Ejaan betul:', ['Kesinambungan', 'Kesinabungan', 'Kesinambungaan', 'Kesinambungan (betul)'], 0),
  q('ms-6-087', 6, 'malay', 'Kata hubung \\', [' dan \\\\', ' menunjukkan?', 'Tujuan', 'Syarat'], 2),
  q('ms-6-088', 6, 'malay', '\\\\', [' — klausa relatif?', 'yang tekun itu', 'lulus dengan cemerlang', 'murid lulus'], 0),
  q('ms-6-089', 6, 'malay', 'Dalam penulisan saintifik, format rujukan menggunakan?', ['Gaya penulisan peribadi', 'Sistem sitasi standard seperti APA', 'Tiada rujukan perlu', 'Hanya nama penulis'], 1),
  q('ms-6-090', 6, 'malay', 'Nilai bertanggungjawab bermaksud?', ['Melakukan sesuatu sesuka hati', 'Menunaikan tanggungjawab dengan penuh dedikasi', 'Hanya bila diperhatikan', 'Hanya bila mendapat ganjaran'], 1),
  q('ms-6-091', 6, 'malay', 'Kata hubung \\\\', [' berfungsi untuk?', 'Menunjukkan syarat', 'Menunjukkan tujuan', 'Menambah penekanan/lebih-lebih lagi'], 2),
  q('ms-6-092', 6, 'malay', '\\\\', [' — klausa relatif?', 'yang tinggi itu', 'mengejutkan semua orang', 'harga mengejutkan'], 0),
  q('ms-6-093', 6, 'malay', 'Dalam penulisan kreatif, plot yang berkesan?', ['Hanya menceritakan latar', 'Mempunyai konflik yang menarik dan peleraian memuaskan', 'Hanya ada watak', 'Tiada konflik'], 1),
  q('ms-6-094', 6, 'malay', 'Nilai keterbukaan bermaksud?', ['Tidak mahu mendengar pandangan lain', 'Bersedia menerima idea dan pandangan yang berbeza', 'Hanya ikut satu pandangan', 'Bersikap tegar'], 1),
  q('ms-6-095', 6, 'malay', '\\\\', [' terbentuk daripada?', 'adil + ke-...-an', 'ke- + adil + -an', 'Kedua-duanya tepat'], 2),
  q('ms-6-096', 6, 'malay', 'Ejaan betul:', ['Kemampuan', 'Kemampuaan', 'Kemampuaan', 'Kemanpuan'], 0),
  q('ms-6-097', 6, 'malay', 'Kata hubung \\\\', [' menunjukkan?', 'Sebab', 'Tujuan', 'Pertentangan/kontras'], 2),
  q('ms-6-098', 6, 'malay', '\\\\', [' — klausa relatif?', 'yang bijaksana itu', 'membuat keputusan yang adil', 'hakim adil'], 0),
  q('ms-6-099', 6, 'malay', 'Dalam drama, monolog ialah?', ['Dialog antara dua watak', 'Ucapan seorang watak kepada dirinya atau penonton', 'Nyanyian sahaja', 'Tarian sahaja'], 1),
  q('ms-6-100', 6, 'malay', 'Nilai semangat kekitaan bermaksud?', ['Mengutamakan diri sendiri', 'Perasaan setia dan bersatu padu dalam kumpulan', 'Hanya untuk keluarga', 'Tidak peduli orang lain'], 1),
];
